// 용어 풀이: 대시보드에 나오는 약어와 전문 용어를 비전문가도 읽을 수 있게 풉니다.
// 키(k)는 <Term k="SDR" /> 와 용어 풀이 페이지(#/glossary)가 함께 씁니다.
// term = 화면 표기, en = 원어, ko = 한국어 이름(본문 첫 등장 괄호에 씁니다), short = 한 줄 풀이, long = 조금 더 자세한 풀이
// where 는 그 용어가 나오는 대시보드 페이지 id 입니다. 페이지 문구를 고치면 함께 고칩니다.

export type GlossCat = 'pv' | 'signal' | 'reg' | 'eval' | 'ai' | 'agent' | 'bio' | 'data' | 'brain'

export const GLOSS_CAT: Record<GlossCat, { name: string; color: string }> = {
  pv: { name: '약물감시 기본', color: '#37e6ff' },
  signal: { name: '신호 통계', color: '#ff4fd8' },
  reg: { name: '규제 · 기관 · 기준', color: '#ffcc4d' },
  eval: { name: '평가 지표 · 통계 검정', color: '#4d8dff' },
  ai: { name: 'AI 모델 · 판단 구조', color: '#76b900' },
  agent: { name: '에이전트 · 보안', color: '#e2a74e' },
  bio: { name: '구조생물학 · 신약 탐색', color: '#3ddc97' },
  data: { name: '데이터 · 시스템', color: '#a58bff' },
  brain: { name: '초파리 커넥텀', color: '#ff8f3a' },
}

export interface GlossEntry {
  term: string
  en?: string
  ko: string
  short: string
  long?: string
  cat: GlossCat
  aliases?: string[]
  where?: string[]
}

export const GLOSSARY: Record<string, GlossEntry> = {
  // ─── 약물감시 기본 ───
  PV: { term: 'PV', en: 'Pharmacovigilance', ko: '약물감시', cat: 'pv', aliases: ['약물감시', 'pharmacovigilance'],
    short: '허가된 약을 쓰는 동안 생기는 이상사례를 모으고 평가해 위험을 찾아내는 일입니다.',
    long: '임상시험에서 드러나지 않은 드문 부작용이나 늦게 나타나는 부작용이 시판 뒤에 보고됩니다. 제약사와 규제기관은 이 보고를 계속 모아 살펴봅니다. STEP 2 FlyVigilance가 돕는 업무입니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'signals', 'warehouse', 'bench'] },
  AE: { term: '이상사례', en: 'Adverse Event (AE)', ko: '약을 쓴 뒤 생긴 좋지 않은 일', cat: 'pv', aliases: ['AE', 'adverse event'],
    short: '약을 쓴 뒤 생긴 모든 좋지 않은 일입니다. 약 때문인지는 아직 따지지 않은 상태입니다.',
    long: '예를 들어 약을 먹은 뒤 넘어져 다친 일도 이상사례로 보고될 수 있습니다. 약과의 관련성은 인과성 평가에서 따로 따집니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea'] },
  ADR: { term: '약물이상반응', en: 'Adverse Drug Reaction (ADR)', ko: '약과의 관련성을 배제할 수 없는 이상사례', cat: 'pv', aliases: ['ADR'],
    short: '이상사례 가운데 약과의 인과관계를 배제할 수 없는 반응입니다.',
    long: '국내 15일 신속보고는 "중대한 약물이상반응"을 기준으로 삼습니다. 보고자와 품목허가권자가 모두 관련 없다고 판단한 경우에만 약물이상반응에서 빠집니다.',
    where: ['korea'] },
  ICSR: { term: 'ICSR', en: 'Individual Case Safety Report', ko: '개별 이상사례 보고', cat: 'pv',
    short: '환자 한 명에게 생긴 이상사례 한 건을 적은 보고서입니다.',
    long: '의심 약, 이상반응, 환자 정보(나이·성별), 경과와 결과가 들어갑니다. FAERS의 사례 한 건이 ICSR 하나입니다.',
    where: ['problem', 'triage', 'bench'] },
  triage: { term: '트리아지', en: 'Triage', ko: '사례 분류', cat: 'pv', aliases: ['사례 분류', 'triage'],
    short: '들어온 보고가 얼마나 급한지 가려 처리 경로를 정하는 첫 단계입니다. 응급실의 환자 분류와 같은 일입니다.',
    long: 'FlyVigilance는 보고마다 사람 우선(신속보고 후보), System-2 검토, 추가정보 요청, 모니터링, 종결 중 하나로 보냅니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'bench', 'cli', 'korea'] },
  seriousness: { term: '중대성', en: 'Seriousness', ko: '결과가 심각한 사례인지 여부', cat: 'pv', aliases: ['중대', 'serious'],
    short: '사망, 생명 위협, 입원, 장애, 선천 기형처럼 결과가 심각한 사례인지 여부입니다.',
    long: 'ICH E2A가 정의합니다. 증상이 얼마나 센지를 뜻하는 "심각도(severity)"와는 다른 개념입니다. 두통이 아주 심해도 입원하지 않았다면 중대 사례가 아닐 수 있습니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'bench', 'architecture'] },
  expectedness: { term: '예측성', en: 'Expectedness', ko: '허가사항에 이미 적힌 반응인지 여부', cat: 'pv', aliases: ['예상하지 못한', 'expected', 'unexpected'],
    short: '그 반응이 허가사항(라벨)에 이미 적혀 있는지 여부입니다. 적혀 있지 않으면 "예상하지 못한" 반응입니다.',
    long: '라벨에 없는 반응은 새로운 위험일 수 있어 더 빨리 살펴봅니다. FlyVigilance는 이 값을 모델 기억이 아니라 FDA 라벨 원문 조회로 정합니다.',
    where: ['problem', 'triage', 'validation', 'bench', 'architecture'] },
  causality: { term: '인과성', en: 'Causality', ko: '약이 반응을 일으켰을 가능성', cat: 'pv', aliases: ['인과', 'causality'],
    short: '그 약이 그 반응을 일으켰을 가능성이 얼마나 되는지에 대한 평가입니다.',
    long: 'WHO-UMC 기준이나 한국형 인과성 평가 알고리즘으로 매깁니다. 불균형 통계(SDR)는 보고 사이의 연관성일 뿐 개별 환자의 인과를 뜻하지 않습니다.',
    where: ['problem', 'triage', 'korea', 'validation', 'agent', 'architecture', 'overview'] },
  label: { term: '라벨', en: 'Drug label (허가사항)', ko: '허가사항 · 약의 공식 설명서', cat: 'pv', aliases: ['허가사항', '허가 라벨', 'label'],
    short: '규제기관이 허가한 약의 공식 설명서입니다. 경고, 이상반응, 금기 등이 절별로 적혀 있습니다.',
    long: '미국은 FDA 라벨, 국내는 식약처 허가사항(사용상의 주의사항)입니다. 라벨에 기재됐다고 해서 이 환자에게 인과가 확인된 것은 아닙니다.',
    where: ['overview', 'problem', 'triage', 'korea', 'signals', 'timemachine', 'validation', 'bench', 'architecture', 'skills'] },
  boxed: { term: '박스 경고', en: 'Boxed warning', ko: '라벨 맨 위의 가장 강한 경고', cat: 'pv', aliases: ['boxed warning'],
    short: 'FDA 라벨 맨 위 검은 테두리 상자에 적는 가장 강한 경고입니다.',
    where: ['signals', 'triage'] },
  contraindication: { term: '금기', en: 'Contraindication', ko: '쓰면 안 되는 조건', cat: 'pv',
    short: '이런 환자에게는 이 약을 쓰면 안 된다고 라벨에 적은 조건입니다.',
    long: '금기 절에 반응 이름이 나와도 "이상반응으로 라벨에 있음"으로 세지 않습니다(약사 검토 반영).',
    where: ['overview'] },
  indication: { term: '적응증', en: 'Indication', ko: '약을 쓰도록 허가된 질환', cat: 'pv',
    short: '그 약을 쓰도록 허가된 질환입니다.',
    long: '앓고 있던 병의 증상이 이상반응처럼 보고되는 "적응증 교란"이 있어 조심해서 읽습니다.',
    where: ['triage', 'signals', 'skills'] },
  expedited: { term: '신속보고', en: 'Expedited reporting', ko: '정해진 기한 안에 규제기관에 보고하는 의무', cat: 'pv', aliases: ['15일', 'expedite', '신속보고 기한'],
    short: '중요한 사례를 정해진 기한(보통 15일) 안에 규제기관에 보고하는 의무입니다.',
    long: '미국은 "중대하고 예상하지 못한" 사례, 한국은 "중대한 약물이상반응"(인과관계를 배제할 수 없는 반응)이 15일 보고 대상입니다. FlyVigilance는 두 규정 모드를 모두 둡니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'architecture', 'warehouse'] },
  SUSAR: { term: 'SUSAR', en: 'Suspected Unexpected Serious Adverse Reaction', ko: '예상하지 못한 중대한 이상반응 의심 사례', cat: 'pv',
    short: '임상시험 중에 생긴, 중대하면서 예상하지 못한 이상반응 의심 사례입니다. 신속보고 대상입니다.',
    long: '시판 후 보고에서도 "중대 + 예상하지 못함"이라는 같은 발상이 미국 15일 보고 기준으로 쓰입니다. FlyVigilance의 미국 규정 모드가 이 기준을 따릅니다.',
    where: ['mission'] },
  outcome: { term: '결과 코드', en: 'FAERS outcome codes', ko: '보고에 붙는 결과 표시', cat: 'pv', aliases: ['DE', 'LT', 'HO', 'outcome'],
    short: 'FAERS 보고에 붙는 결과 표시입니다. DE 사망, LT 생명 위협, HO 입원, DS 장애, CA 선천 기형, RI 중재 필요, OT 기타 중대가 있습니다.',
    long: '이 코드가 하나라도 있으면 중대 사례로 봅니다. 평가에서는 이 코드를 입력에서 가려, 모델이 정답을 보지 않고 서술만으로 판단하게 했습니다.',
    where: ['overview', 'mission', 'triage', 'bench', 'warehouse', 'architecture'] },
  autoqueue: { term: '자동 큐', en: 'Auto queue', ko: '사람도 System-2도 따로 보지 않는 사례 묶음', cat: 'pv',
    short: '종결이나 모니터링으로 보내져 사람도 System-2도 따로 보지 않는 사례 묶음입니다.',
    long: '중대 사례가 자동 큐에 남으면 놓친 것입니다. 비교 실험은 자동 큐에 남은 중대 사례 수를 핵심 지표로 봅니다.',
    where: ['overview', 'problem', 'mission', 'bench', 'architecture'] },
  pvclass: { term: 'PV 분류', en: 'PV classification', ko: '라벨 상태 × SDR로 매긴 검토 우선순위', cat: 'pv', aliases: ['근거 등급'],
    short: '라벨 기재 여부와 SDR 여부를 조합해 검토 우선순위(1~5)를 매긴 분류입니다.',
    long: '1 검토가 필요한 SDR(라벨 미기재 + SDR)부터 5 해당 없음까지입니다. 모두 "후보"이며 최종 분류는 허가권자와 규제기관이 정합니다. 한 글자 등급(A/B/C/L/D/U)은 팀 시제품과 맞추려고 함께 표시합니다.',
    where: ['overview', 'triage', 'signals', 'architecture'] },
  bias: { term: '보고 편향', en: 'Reporting bias', ko: '특정 보고가 한꺼번에 몰려 통계가 부풀려지는 현상', cat: 'pv', aliases: ['보고자 편향', 'stimulated reporting'],
    short: '소송이나 언론 보도 때문에 특정 보고가 한꺼번에 몰려 통계가 부풀려지는 현상입니다.',
    long: '변호사·소비자 보고 비율로 표시하고, 변호사 보고를 뺀 뒤에도 SDR이 유지되는지 함께 봅니다. 예: 이소트레티노인 × 염증성 장질환.',
    where: ['overview', 'signals', 'timemachine', 'skills', 'triage'] },
  role: { term: 'PS · SS · C', en: 'Primary suspect · Secondary suspect · Concomitant', ko: '보고 안에서 약의 역할', cat: 'pv', aliases: ['역할 코드', 'PS', 'SS'],
    short: '보고 안에서 약이 맡은 역할입니다. PS는 주 의심약, SS는 부 의심약, C는 함께 먹던 병용약입니다.',
    where: ['triage', 'korea', 'warehouse', 'architecture'] },
  dechal: { term: 'dechal · rechal', en: 'Dechallenge · Rechallenge', ko: '약을 끊거나 다시 썼을 때의 반응 변화', cat: 'pv',
    short: '약을 끊었더니 반응이 사라졌는지(dechallenge), 다시 썼더니 재발했는지(rechallenge)입니다.',
    long: '둘 다 양성이면 인과성을 강하게 시사합니다. 인과성 평가의 핵심 단서입니다.',
    where: ['triage', 'korea'] },

  // ─── 신호 통계 ───
  disproportionality: { term: '불균형 분석', en: 'Disproportionality analysis', ko: '보고 비율을 다른 약과 비교하는 통계', cat: 'signal', aliases: ['불균형 지표', 'disproportionality'],
    short: '특정 약과 특정 반응이 함께 보고된 비율을 다른 약 전체와 비교하는 통계 방법입니다.',
    long: 'PRR, ROR, IC가 대표 지표입니다. 보고 사이의 연관성만 보여 주며, 인과나 발생률을 알려 주지 않습니다(과잉해석 규칙 R1, R2).',
    where: ['overview', 'problem', 'signals', 'timemachine', 'warehouse', 'skills', 'cli', 'architecture'] },
  SDR: { term: 'SDR', en: 'Signal of Disproportionate Reporting', ko: '불균형 보고 신호', cat: 'signal',
    short: '특정 약·이상반응 조합이 다른 약보다 유난히 많이 보고되는 통계 신호입니다. 인과를 확인하기 전 단계입니다.',
    long: '이 프로젝트는 Evans 기준, ROR₀₂₅ > 1, IC₀₂₅ > 0 세 가지를 모두 넘으면 SDR로 표시합니다(3중 기준). SDR은 검토를 시작할 이유이지 검증된 신호가 아닙니다(EU GVP Module IX).',
    where: ['overview', 'problem', 'mission', 'triage', 'signals', 'timemachine', 'validation', 'warehouse', 'architecture', 'skills', 'cli'] },
  signal: { term: '신호', en: 'Signal', ko: '검증을 거친 새 위험 정보', cat: 'signal', aliases: ['검증된 신호', 'validated signal'],
    short: '약과 이상반응 사이에 새로운 인과 가능성이 있다는 정보로, 검증 절차를 거친 것입니다.',
    long: 'SDR은 통계 기준만 넘은 상태이고, 사례 검토·문헌·기전 확인을 거쳐야 신호가 됩니다.',
    where: ['signals', 'timemachine', 'mission', 'triage'] },
  PRR: { term: 'PRR', en: 'Proportional Reporting Ratio', ko: '비례 보고 비', cat: 'signal',
    short: '이 약 보고 중 해당 반응의 비율을, 다른 약 보고 중 그 반응의 비율로 나눈 값입니다.',
    long: '1보다 크면 이 약에서 그 반응이 더 자주 보고된다는 뜻이고, PRR 2는 두 배입니다. 보고 비율이지 발생률이 아니며, PRR이 높다고 인과가 증명되지 않습니다.',
    where: ['overview', 'problem', 'triage', 'korea', 'signals', 'timemachine', 'validation', 'architecture', 'cli'] },
  ROR: { term: 'ROR', en: 'Reporting Odds Ratio', ko: '보고 오즈비', cat: 'signal', aliases: ['ROR₀₂₅', 'ROR025', 'ror025'],
    short: 'PRR처럼 보고 비율을 비교하되 오즈(odds)로 계산한 값입니다.',
    long: 'ROR₀₂₅는 95% 신뢰구간의 하한입니다. 하한이 1을 넘으면 우연만으로는 설명하기 어려운 불균형으로 봅니다.',
    where: ['mission', 'triage', 'korea', 'signals', 'validation', 'warehouse', 'architecture', 'cli'] },
  IC025: { term: 'IC₀₂₅', en: 'Information Component, lower 95% bound', ko: '정보 성분 하한', cat: 'signal', aliases: ['IC', 'IC025', 'BCPNN', 'ic025'],
    short: '관측된 보고 수가 기대치보다 얼마나 많은지 log₂로 나타낸 베이지안 지표(IC)의 95% 하한입니다.',
    long: 'IC₀₂₅가 0보다 크면 기대보다 많이 보고됐다고 봅니다. WHO-UMC가 쓰는 BCPNN(베이지안 신뢰 전파 신경망) 방법으로 계산합니다. 보고 수가 적을 때 과장되지 않도록 보수적으로 잡은 값입니다.',
    where: ['overview', 'mission', 'triage', 'signals', 'timemachine', 'validation', 'architecture', 'cli', 'korea'] },
  evans: { term: 'Evans 기준', en: 'Evans criteria (2001)', ko: '고전적 불균형 판정 기준', cat: 'signal', aliases: ['Evans'],
    short: 'PRR ≥ 2, 카이제곱(χ²) ≥ 4, 함께 보고된 사례 a ≥ 3을 모두 만족하면 불균형으로 보는 고전 기준입니다.',
    where: ['mission', 'signals', 'timemachine', 'validation', 'warehouse'] },
  triple: { term: '3중 기준', en: 'Triple criteria', ko: 'Evans ∧ ROR₀₂₅ > 1 ∧ IC₀₂₅ > 0', cat: 'signal', aliases: ['3중 기준 SDR'],
    short: 'Evans 기준, ROR₀₂₅ > 1, IC₀₂₅ > 0 세 가지를 모두 넘는 경우입니다. 이 프로젝트의 SDR 판정 기준입니다.',
    long: '세 지표가 모두 동의할 때만 SDR로 표시해 오경보를 줄입니다.',
    where: ['overview', 'problem', 'signals', 'validation', 'warehouse', 'architecture'] },
  chi2: { term: 'χ²', en: 'Chi-square (Yates)', ko: '카이제곱 통계량', cat: 'signal', aliases: ['카이제곱', 'chi2'],
    short: '관측 건수와 기대 건수의 차이가 우연으로 설명되는지 보는 통계량입니다. Evans 기준은 4 이상을 봅니다.',
    where: ['signals', 'validation', 'architecture'] },
  aE: { term: 'a · E', en: 'Observed (a) · Expected (E) count', ko: '함께 보고된 사례 수 · 기대 사례 수', cat: 'signal', aliases: ['a', 'E', 'co-reported'],
    short: 'a는 이 약과 이 반응이 함께 보고된 사례 수, E는 우연이라면 기대되는 사례 수입니다.',
    long: 'a가 E보다 훨씬 크면 불균형 지표가 커집니다. a가 3 미만이면 통계가 불안정해 판정하지 않습니다.',
    where: ['triage', 'signals', 'timemachine', 'validation', 'warehouse'] },
  CI: { term: '95% CI', en: 'Confidence Interval', ko: '95% 신뢰구간', cat: 'signal', aliases: ['신뢰구간', 'CI'],
    short: '추정값이 표본의 우연 때문에 흔들릴 수 있는 범위입니다.',
    long: '하한이 기준값(예: 1)을 넘으면 우연으로 보기 어렵다고 판단합니다.',
    where: ['signals', 'validation', 'architecture'] },
  table22: { term: '2×2 표', en: 'Two-by-two contingency table', ko: '약 × 반응 네 칸 표', cat: 'signal',
    short: '"이 약인가 아닌가" × "이 반응인가 아닌가"로 보고를 나눈 네 칸 표입니다. 불균형 지표는 모두 이 표에서 계산합니다.',
    where: ['problem', 'triage'] },
  leadtime: { term: '선행 시간', en: 'Lead time', ko: '첫 SDR이 규제 조치보다 앞선 기간', cat: 'signal', aliases: ['선행 일수', 'lead time'],
    short: '첫 SDR이 규제 조치(라벨 변경, 안전성 서한)보다 며칠 먼저 섰는지입니다.',
    long: '양수면 조치보다 먼저 통계 기준을 넘었다는 뜻입니다. 공개 분기 파일로 다시 계산한 값이라 FDA 내부 검토 시점과는 다를 수 있습니다.',
    where: ['problem', 'timemachine'] },
  kr_signal: { term: '실마리정보', en: 'Signal information (KIDS)', ko: '국내에서 찾은 확인이 필요한 안전성 단서', cat: 'signal',
    short: '국내에서 통계와 사례 검토로 찾은 "확인이 필요한 안전성 단서"입니다. 해외의 신호(signal)에 해당합니다.',
    where: ['korea'] },

  // ─── 규제 · 기관 · 기준 ───
  FDA: { term: 'FDA', en: 'U.S. Food and Drug Administration', ko: '미국 식품의약국', cat: 'reg',
    short: '미국의 의약품 허가·안전 규제기관입니다.',
    where: ['overview', 'problem', 'triage', 'korea', 'timemachine', 'validation', 'warehouse'] },
  EMA: { term: 'EMA', en: 'European Medicines Agency', ko: '유럽의약품청', cat: 'reg',
    short: '유럽연합의 의약품 허가·안전 규제기관입니다.',
    where: ['overview', 'triage', 'bench', 'architecture'] },
  MFDS: { term: '식약처', en: 'Ministry of Food and Drug Safety (MFDS)', ko: '식품의약품안전처', cat: 'reg', aliases: ['MFDS', '식품의약품안전처'],
    short: '국내 의약품 허가·안전 규제기관입니다.',
    long: '허가사항 변경 명령, 안전성 서한, 회수 같은 조치를 냅니다. 국내 보고서식(공고 제2023-057호)도 식약처가 정합니다.',
    where: ['problem', 'korea'] },
  KAERS: { term: 'KAERS', en: 'Korea Adverse Event Reporting System', ko: '국내 이상사례 보고 시스템', cat: 'reg',
    short: '한국의약품안전관리원이 운영하는 국내 이상사례 보고 시스템입니다.',
    where: ['problem', 'korea'] },
  KIDS: { term: 'KIDS', en: 'Korea Institute of Drug Safety & Risk Management', ko: '한국의약품안전관리원', cat: 'reg',
    short: '국내 이상사례 보고를 모아 분석하고 실마리정보를 내는 기관입니다.',
    where: ['korea'] },
  regional: { term: '지역의약품안전센터', en: 'Regional Pharmacovigilance Center', ko: '개별 사례의 인과성을 평가하는 국내 센터', cat: 'reg',
    short: '병원 등에 지정된 국내 28곳의 센터로, 개별 이상사례의 인과성을 평가합니다.',
    where: ['korea'] },
  VigiBase: { term: 'VigiBase', en: 'WHO global ICSR database', ko: 'WHO 국제 이상사례 데이터베이스', cat: 'reg',
    short: '세계보건기구(WHO)가 여러 나라의 이상사례 보고를 모아 둔 데이터베이스입니다.',
    where: ['korea'] },
  DME: { term: 'DME', en: 'Designated Medical Event (EMA)', ko: 'EMA가 지정한 특별 주의 이상사례', cat: 'reg', aliases: ['EMA DME', '지정 의학적 사건'],
    short: 'EMA가 드물지만 심각해서 한 건만 보고돼도 살펴봐야 한다고 지정한 이상반응 목록입니다.',
    long: '스티븐스-존슨 증후군, 무과립구증 같은 반응이 들어 있습니다. FlyVigilance는 이 목록의 MedDRA PT 62개가 보고되면 점수와 관계없이 사람 검토로 보내는 안전망으로 씁니다.',
    where: ['overview', 'triage', 'bench', 'architecture', 'signals'] },
  ICH: { term: 'ICH', en: 'International Council for Harmonisation', ko: '의약품 국제조화위원회', cat: 'reg', aliases: ['ICH E2A', 'ICH E2D', 'E2A', 'E2D'],
    short: '각국 규제기관과 제약업계가 함께 만든 의약품 규정 표준 기구입니다.',
    long: 'E2A는 "중대"의 정의와 신속보고 원칙을, E2D는 시판 후 안전성 보고 관리를 다루는 가이드라인입니다.',
    where: ['overview', 'problem', 'triage', 'architecture'] },
  ICH4: { term: 'ICH 최소 4요소', en: 'ICH minimum criteria for a valid ICSR', ko: '유효한 보고의 최소 조건', cat: 'reg', aliases: ['최소 4요소', 'ICH 4요소'],
    short: '유효한 보고로 인정하는 최소 조건입니다. 확인 가능한 보고자, 확인 가능한 환자, 의심 약, 이상사례 네 가지가 있어야 합니다.',
    long: '하나라도 빠지면 FlyVigilance 규칙 게이트가 모델을 부르지 않고 추가정보 요청으로 보냅니다.',
    where: ['overview', 'triage', 'architecture'] },
  GVP: { term: 'GVP', en: 'Good Pharmacovigilance Practices (EU)', ko: '약물감시 모범 실무 지침', cat: 'reg', aliases: ['GVP Module IX', 'GVP Module VI'],
    short: 'EMA의 약물감시 실무 지침입니다. Module VI는 이상사례 보고를, Module IX는 신호 관리를 다룹니다.',
    where: ['problem', 'signals', 'triage'] },
  WHOUMC: { term: 'WHO-UMC', en: 'WHO Uppsala Monitoring Centre causality system', ko: '세계보건기구 인과성 평가 기준', cat: 'reg', aliases: ['WHO UMC'],
    short: '개별 사례의 인과성을 여섯 단계(확실함 · 상당히 확실함 · 가능함 · 가능성 적음 · 평가 곤란 · 평가 불가)로 매기는 국제 기준입니다.',
    where: ['triage', 'korea', 'architecture'] },
  kralgo: { term: '한국형 인과성 평가 알고리즘', en: 'Korean causality assessment algorithm ver 2.0', ko: '국내 점수표식 인과성 평가', cat: 'reg', aliases: ['한국형 알고리즘', 'ver 2.0'],
    short: '국내 지역의약품안전센터가 쓰는 점수표식 인과성 평가 방법(ver 2.0)입니다. 8개 항목 점수를 더해 등급을 정합니다.',
    where: ['korea', 'architecture', 'cli'] },
  E2B: { term: 'E2B(R3)', en: 'ICH E2B(R3) electronic ICSR format', ko: '이상사례 전자 보고 국제 표준 서식', cat: 'reg',
    short: '이상사례 보고를 전자 문서로 주고받는 국제 표준 서식입니다.',
    where: ['architecture'] },
  MedDRA: { term: 'MedDRA PT', en: 'Medical Dictionary for Regulatory Activities · Preferred Term', ko: '이상반응 표준 용어', cat: 'reg', aliases: ['MedDRA', 'PT'],
    short: '이상반응 이름을 통일한 국제 의학 용어집(MedDRA)의 "대표 용어(PT)" 단계입니다.',
    long: '같은 반응을 여러 표현으로 적어도 하나의 PT로 모읍니다. 예: thrombocytopenia(혈소판감소증).',
    where: ['mission', 'triage', 'signals', 'validation', 'bench', 'warehouse', 'architecture', 'overview'] },
  openFDA: { term: 'openFDA · DailyMed', en: 'openFDA API · DailyMed', ko: 'FDA 공개 데이터 조회 창구 · 미국 약 라벨 원문 사이트', cat: 'reg', aliases: ['openFDA', 'DailyMed'],
    short: 'openFDA는 FDA 데이터를 조회하는 공개 API이고, DailyMed는 미국 약 라벨 원문을 공개하는 사이트입니다.',
    where: ['overview', 'mission', 'triage', 'korea', 'bench', 'architecture'] },
  PubMed: { term: 'PubMed · MEDLINE · PMID', en: 'PubMed · MEDLINE · PubMed ID', ko: '의학 논문 검색 · 색인 · 논문 번호', cat: 'reg', aliases: ['PubMed', 'MEDLINE', 'PMID'],
    short: 'PubMed는 의학 논문 검색 서비스, MEDLINE은 논문의 연구 설계 등을 색인한 데이터베이스, PMID는 논문 고유 번호입니다.',
    where: ['overview', 'triage', 'korea', 'validation', 'architecture', 'signals', 'skills'] },
  refset: { term: '참조 세트', en: 'Reference set', ko: '정답을 미리 정해 둔 평가용 목록', cat: 'reg', aliases: ['OMOP', 'EU-ADR', 'Harpaz'],
    short: '알려진 양성·음성 약물–반응 쌍을 정답으로 미리 정해 둔 공개 평가용 목록입니다.',
    long: 'OMOP(결과 4종), EU-ADR(결과 10종), Harpaz(2013년 라벨 변경 기반, 시점 정보 포함)를 씁니다. 공인된 조합을 가려내는지를 재며, 개별 사례의 인과성을 재지 않습니다.',
    where: ['overview', 'problem', 'validation', 'architecture'] },
  prospective: { term: '전향 검증', en: 'Prospective (time-indexed) validation', ko: '그 시점까지의 자료만으로 미래를 맞히는 검증', cat: 'reg', aliases: ['전향'],
    short: '미래 정보를 쓰지 않고 그 시점까지의 자료만으로 나중에 일어날 일을 맞히는지 보는 검증입니다.',
    long: '여기서는 2013년 이전 보고(구형 AERS)만으로 2013년 라벨 변경을 미리 SDR로 잡았는지 봤습니다.',
    where: ['overview', 'problem', 'validation', 'architecture'] },

  // ─── 평가 지표 · 통계 검정 ───
  AUC: { term: 'AUC', en: 'Area Under the ROC Curve (AUROC)', ko: '판별 정확도', cat: 'eval', aliases: ['AUROC'],
    short: '양성과 음성을 얼마나 잘 가르는지 나타내는 0~1 점수입니다. 0.5는 무작위, 1은 완벽입니다.',
    long: 'ROC 곡선 아래 넓이입니다. 무작위로 양성 하나와 음성 하나를 골랐을 때 양성에 더 높은 점수를 줄 확률과 같습니다.',
    where: ['overview', 'validation', 'bench', 'architecture'] },
  ROC: { term: 'ROC', en: 'Receiver Operating Characteristic curve', ko: '민감도–오경보율 곡선', cat: 'eval',
    short: '판정 기준을 바꿔 가며 민감도(세로)와 오경보율(가로, 1 − 특이도)을 그린 곡선입니다. 왼쪽 위로 붙을수록 좋습니다.',
    where: ['validation'] },
  sens: { term: '민감도 · 특이도', en: 'Sensitivity (TPR) · Specificity', ko: '놓치지 않는 정도 · 오경보를 내지 않는 정도', cat: 'eval', aliases: ['민감도', '특이도', 'TPR', 'FPR'],
    short: '민감도는 실제 양성 중 잡아낸 비율, 특이도는 실제 음성 중 음성으로 맞게 거른 비율입니다.',
    long: '민감도가 높으면 놓치는 것이 적고, 특이도가 높으면 오경보가 적습니다. 둘은 보통 서로 맞바꿉니다.',
    where: ['validation', 'bench'] },
  PPV: { term: 'PPV', en: 'Positive Predictive Value', ko: '양성 예측도', cat: 'eval',
    short: '양성이라고 판정한 것 가운데 실제 양성의 비율입니다. 경보가 울렸을 때 믿을 만한 정도입니다.',
    where: ['overview', 'problem', 'validation', 'architecture'] },
  confusion: { term: 'TP · FP · TN · FN', en: 'True/False Positive/Negative', ko: '참양성 · 거짓양성 · 참음성 · 거짓음성', cat: 'eval', aliases: ['혼동 행렬', 'confusion matrix', '오경보'],
    short: '맞게 잡은 양성(TP), 오경보(FP), 맞게 거른 음성(TN), 놓친 양성(FN)입니다. 이 넷을 교차한 표가 혼동 행렬입니다.',
    where: ['validation', 'problem'] },
  McNemar: { term: 'McNemar 검정', en: "McNemar's exact test", ko: '짝지은 비교 검정', cat: 'eval', aliases: ['McNemar'],
    short: '같은 사례들에 두 방법을 적용했을 때, 한쪽만 맞힌 사례 수가 우연 이상으로 다른지 보는 검정입니다.',
    long: '같은 440건을 두 조건에 넣었으므로 사례끼리 짝을 지어 비교합니다. 두 조건이 똑같이 맞히거나 똑같이 틀린 사례는 차이에 영향을 주지 않습니다.',
    where: ['overview', 'bench'] },
  pvalue: { term: 'p값', en: 'p-value', ko: '우연히 이만한 차이가 나올 확률', cat: 'eval', aliases: ['p-value', 'p ='],
    short: '실제로는 차이가 없다고 가정할 때 지금만큼 큰 차이가 우연히 나올 확률입니다.',
    long: '보통 0.05보다 작으면 통계적으로 유의하다고 봅니다. 3.6×10⁻⁴⁸ 같은 값은 우연일 가능성이 사실상 없다는 뜻입니다. 효과의 크기를 뜻하지는 않습니다.',
    where: ['overview', 'problem', 'bench', 'architecture'] },
  bootstrap: { term: '부트스트랩', en: 'Bootstrap', ko: '표본을 다시 뽑아 흔들림을 재는 방법', cat: 'eval',
    short: '표본을 여러 번 다시 뽑아 추정값이 얼마나 흔들리는지 재는 방법입니다.',
    long: '두 방법의 AUC 차이에 대한 95% 부트스트랩 구간이 0을 포함하지 않으면 "유의한 차이"로 봅니다.',
    where: ['validation'] },
  spearman: { term: 'Spearman ρ', en: 'Spearman rank correlation', ko: '순위 상관', cat: 'eval', aliases: ['Spearman', 'Pearson', 'ρ'],
    short: '두 값의 순위가 얼마나 같이 움직이는지 나타내는 −1~1 값입니다. 1이면 순위가 완전히 같습니다.',
    long: 'Boltz-2가 예측한 친화도 순위가 실측 순위와 얼마나 맞는지 잴 때 씁니다. Pearson은 순위 대신 값 자체의 직선 관계를 봅니다.',
    where: ['overview', 'discovery', 'd-boltz'] },
  MAE: { term: 'MAE · RMSE', en: 'Mean Absolute Error · Root-Mean-Square Error', ko: '평균 오차', cat: 'eval', aliases: ['MAE', 'RMSE'],
    short: '예측과 실측이 평균적으로 얼마나 다른지입니다. RMSE는 큰 오차에 더 무게를 둡니다.',
    where: ['discovery', 'd-boltz'] },
  EF: { term: 'EF', en: 'Enrichment Factor', ko: '농축 계수', cat: 'eval', aliases: ['상위 25% EF'],
    short: '상위로 고른 후보에 진짜 강한 물질이 무작위보다 몇 배 많이 들어 있는지입니다. 1이면 무작위 수준입니다.',
    where: ['discovery', 'd-boltz'] },
  ECE: { term: 'ECE', en: 'Expected Calibration Error', ko: '확률 보정 오차', cat: 'eval', aliases: ['보정'],
    short: '모델이 말한 확률과 실제로 맞힌 비율이 얼마나 어긋나는지입니다. 0에 가까울수록 확률을 믿을 만합니다.',
    where: ['bench', 'architecture'] },
  pct: { term: 'p50 · p90', en: '50th · 90th percentile latency', ko: '응답 시간 중앙값 · 느린 쪽 10% 경계', cat: 'eval', aliases: ['p50', 'p90', '중앙값'],
    short: '여러 번 잰 응답 시간 가운데 중앙값(p50)과, 그보다 느린 것이 10%뿐인 경계(p90)입니다.',
    where: ['overview', 'problem', 'mission', 'bench'] },
  blind: { term: '결과 코드 가림', en: 'Outcome-blind evaluation', ko: '정답 정보를 입력에서 지운 조건', cat: 'eval', aliases: ['맹검', 'blind'],
    short: '정답이 되는 정보(결과 코드)를 입력에서 지워, 모델이 정답을 보고 맞히지 못하게 한 평가 조건입니다.',
    long: '이 프로젝트의 주 측정 조건입니다. 결과 코드를 보여 준 조건은 참고로만 함께 보여 드립니다.',
    where: ['overview', 'problem', 'mission', 'bench', 'architecture'] },
  ablation: { term: '비교 실험', en: 'Ablation study', ko: '부품을 빼거나 바꿔 효과를 재는 실험', cat: 'eval', aliases: ['ablation'],
    short: '부품을 하나씩 빼거나 바꿔 가며 각 부품의 효과를 재는 실험입니다.',
    long: '같은 판단 모델에 질문 하나만 던진 경우와, 규칙 게이트·라벨 조회·7문항·결정 정책을 거친 경우를 같은 사례로 비교했습니다.',
    where: ['problem', 'bench'] },
  baseline: { term: '다수 클래스 기준선', en: 'Majority-class baseline', ko: '모두 흔한 답으로 찍었을 때의 정확도', cat: 'eval',
    short: '모든 사례를 가장 흔한 답으로 찍었을 때의 정확도입니다. 모델은 이보다 나아야 의미가 있습니다.',
    where: ['bench'] },

  design: { term: '연구 설계', en: 'Study design · RCT · cohort · case–control', ko: '논문이 근거를 얻은 방식', cat: 'eval', aliases: ['RCT', '메타분석', '코호트', '환자대조군', '증례보고', '증례군'],
    short: '논문이 어떤 방식으로 근거를 얻었는지입니다. 메타분석(여러 연구 종합), RCT(무작위 대조 임상시험), 코호트(집단 추적), 환자대조군(환자와 대조군 비교), 증례군·증례보고(환자 사례 기술) 순으로 대체로 근거가 강합니다.',
    long: 'FlyVigilance는 PubMed 출판 유형이 있으면 규칙으로, 없으면 비자기회귀 판단 모델로 설계를 판정합니다.',
    where: ['signals', 'triage', 'validation', 'architecture'] },

  // ─── AI 모델 · 판단 구조 ───
  NIM: { term: 'NIM', en: 'NVIDIA Inference Microservices', ko: 'NVIDIA 추론 마이크로서비스', cat: 'ai', aliases: ['build.nvidia.com'],
    short: 'NVIDIA가 AI 모델을 표준 API로 바로 부를 수 있게 포장한 서비스입니다.',
    long: 'build.nvidia.com에서 호출합니다. Nemotron 언어 모델과 BioNeMo 구조 예측 모델을 모두 NIM으로 씁니다. 호스팅 체험 엔드포인트라 대기열 지연이 섞일 수 있습니다.',
    where: ['overview', 'problem', 'mission', 'discovery', 'd-msa', 'd-of3', 'd-diffdock', 'd-boltz', 'bench', 'architecture', 'cli'] },
  LLM: { term: 'LLM', en: 'Large Language Model', ko: '대형 언어 모델', cat: 'ai', aliases: ['생성형 LLM', '생성형 모델'],
    short: '많은 글로 학습해 글을 읽고 쓰는 AI 모델입니다.',
    where: ['problem', 'overview'] },
  Nemotron: { term: 'Nemotron', en: 'NVIDIA Nemotron', ko: 'NVIDIA 언어 모델 계열', cat: 'ai', aliases: ['Nemotron 3 Super', 'Ultra', 'Lightning'],
    short: 'NVIDIA의 언어 모델 계열입니다. 이 프로젝트에서는 평가 메모 작성, 국내 보고 구조화, 크리틱 판정처럼 글을 쓰는 일을 맡습니다.',
    long: 'Nemotron 3 Super를 주로 쓰고, 응답이 없으면 Ultra → 3.5 Lightning 순서로 넘어갑니다(폴백).',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'discovery', 'd-critic', 'bench', 'architecture', 'skills'] },
  guard: { term: 'Safety Guard', en: 'NVIDIA Nemotron Safety Guard · Content Safety', ko: 'NVIDIA 안전 판정 모델', cat: 'ai', aliases: ['Content Safety', 'Nemotron Safety Guard'],
    short: '문장이 안전 정책을 어기는지 판정하는 NVIDIA 가드 모델입니다.',
    long: '여기서는 환자 개별 치료 조언, PRR을 인과로 단정하는 문장, 자발 보고로 낸 발생률 같은 주장을 막습니다. 약물감시 전용 정책은 공식 스킬 nemotron-policy-generator로 만들었습니다.',
    where: ['overview', 'problem', 'triage', 'bench', 'architecture', 'skills'] },
  reranker: { term: '리랭커', en: 'Reranker', ko: '검색 결과를 관련도 순으로 다시 줄 세우는 모델', cat: 'ai',
    short: '검색된 문서 후보를 질문과의 관련도 순으로 다시 줄 세우는 모델입니다.',
    where: ['calls'] },
  embedding: { term: '임베딩', en: 'Embedding', ko: '글을 숫자 벡터로 바꾼 것', cat: 'ai', aliases: ['embeddings', 'embed'],
    short: '글의 뜻을 수천 개의 숫자(벡터)로 바꾼 것입니다. 뜻이 비슷한 글은 벡터도 가깝습니다.',
    long: '이 프로젝트에서는 문헌 재정렬 평가에서 리랭커와 비교하는 기준선으로 Nemotron 3 Embed 를 불렀습니다.',
    where: ['calls'] },
  BioNeMo: { term: 'BioNeMo', en: 'NVIDIA BioNeMo', ko: 'NVIDIA 생명과학 AI 모델 모음', cat: 'bio', aliases: ['health.api.nvidia.com'],
    short: '단백질 구조 예측, 도킹, 친화도 예측 같은 생명과학 모델을 NIM 으로 제공하는 NVIDIA 플랫폼입니다.',
    long: 'MSA-Search, OpenFold3, DiffDock, Boltz-2 를 health.api.nvidia.com 에서 부릅니다. 오래 걸리는 작업은 먼저 202(접수)를 돌려주고, 요청 ID 로 결과를 다시 받아 갑니다.',
    where: ['calls', 'discovery'] },
  NVCF: { term: 'NVCF 요청 ID', en: 'NVIDIA Cloud Functions request ID (NVCF-REQID)', ko: 'NVIDIA 서버가 호출마다 붙이는 접수 번호', cat: 'data', aliases: ['NVCF-REQID', 'nvcf-reqid', 'request id'],
    short: 'NVIDIA 호스팅 API 가 응답 헤더에 붙여 주는 호출별 고유 번호입니다. 택배 송장 번호처럼 이 번호로 그 호출을 특정할 수 있습니다.',
    long: '호출 기록에는 이 번호와 시각·모델·지연·토큰 수 같은 메타데이터만 남기고, API 키와 프롬프트 본문은 남기지 않습니다.',
    where: ['calls'] },
  NAR: { term: '비자기회귀 판단 모델', en: 'Non-autoregressive judgment model', ko: '확률을 한 번에 돌려주는 판단 모델', cat: 'ai', aliases: ['비자기회귀', 'non-autoregressive'],
    short: '글을 한 글자씩 생성하지 않고, 정해진 질문에 대한 확률(예/아니오, 선택지, 점수)을 한 번에 돌려주는 모델입니다. 그래서 빠르고 쌉니다.',
    long: '이 프로젝트는 TypeSafe AI의 Jev를 씁니다. 답이 확률뿐인 판단(반사 트리아지, 과잉해석 판정, 문헌 설계 분류)에 쓰고, 글을 써야 하는 일은 Nemotron이 맡습니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'signals', 'validation', 'bench', 'architecture', 'skills'] },
  AR: { term: '자기회귀 생성', en: 'Autoregressive generation', ko: '한 글자씩 이어 쓰는 방식', cat: 'ai', aliases: ['자기회귀', '생성 방식'],
    short: '앞에서 만든 글자를 보고 다음 글자를 하나씩 이어 쓰는 방식입니다. 일반적인 대화형 LLM이 이렇게 동작합니다.',
    long: '같은 7문항을 이 방식으로 받으면 답을 글로 모두 써야 해서 더 오래 걸립니다.',
    where: ['overview', 'problem', 'mission', 'bench'] },
  Jev: { term: 'Jev', en: 'Jev · TypeSafe AI', ko: 'TypeSafe AI의 비자기회귀 판단 모델', cat: 'ai', aliases: ['TypeSafe AI', 'TypeSafe'],
    short: 'TypeSafe AI가 만든 비자기회귀 판단 엔진입니다. FlyVigilance 안에서 확률 판단을 맡는 부품으로 씁니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'bench', 'architecture', 'skills', 'cli'] },
  token: { term: '토큰', en: 'Token (tok)', ko: '모델이 글을 처리하는 단위', cat: 'ai', aliases: ['tok'],
    short: '모델이 글을 처리하는 단위(대략 단어 조각)입니다. 호출 비용과 속도가 토큰 수에 비례합니다.',
    where: ['problem', 'mission', 'triage', 'bench'] },
  System2: { term: 'System-2', en: 'System-2 deliberation', ko: '숙고 단계', cat: 'ai', aliases: ['숙고', 'Deliberate', 'System 2'],
    short: '빠른 반사 판단으로 부족한 사례만 올려, 근거를 모아 천천히 따져 보는 단계입니다.',
    long: '심리학의 "빠른 사고(System-1) · 느린 사고(System-2)" 구분에서 빌린 이름입니다. 여기서는 NVIDIA Nemotron이 근거 ID를 붙인 평가 메모를 쓰고 크리틱이 검사합니다.',
    where: ['overview', 'mission', 'triage', 'bench', 'architecture'] },
  reflex: { term: '반사 판단', en: 'Reflex triage', ko: '모든 보고를 빠르게 1차 분류하는 층', cat: 'ai', aliases: ['반사 층', 'reflex', '반사 트리아지'],
    short: '모든 보고를 규칙, 라벨 조회, 7문항 확률 판단으로 수백 밀리초 안에 1차 분류하는 층입니다.',
    long: '초파리 뇌의 "반사 회로(lateral horn)"처럼 학습된 판단을 즉시 내린다는 뜻으로 붙인 이름입니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'korea', 'bench', 'architecture'] },
  q7: { term: '7문항 판단', en: 'Seven typed questions', ko: '규제 용어로 쪼갠 일곱 질문', cat: 'ai', aliases: ['7문항'],
    short: '"먼저 봐야 하나?" 한 질문 대신 중대성, 예측성, 인과성, 특수 상황, 우선순위, 다음 행동, 숙고 필요를 따로 묻는 일곱 질문입니다.',
    long: '모두 한 번의 호출로 확률과 함께 받습니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'bench', 'architecture'] },
  policy: { term: '결정 정책', en: 'Decision policy', ko: '확률을 행동과 기한으로 바꾸는 규칙표', cat: 'ai', aliases: ['규정 모드', 'Router'],
    short: '모델이 준 확률을 행동(사람 우선, System-2, 추가정보 요청, 모니터링, 종결)과 보고 기한으로 바꾸는 규칙표입니다.',
    long: '미국·한국 신속보고 기준(규정 모드), 신뢰도가 낮을 때의 상향, DME 안전망을 담습니다.',
    where: ['overview', 'problem', 'triage', 'korea', 'bench', 'architecture'] },
  gate: { term: '규칙 게이트', en: 'Rule gate', ko: '모델을 부르기 전 규칙으로 거르는 관문', cat: 'ai', aliases: ['Rule gate'],
    short: '모델을 부르기 전에 규칙만으로 되는 일(최소 4요소 확인, 결과 코드, 약 역할)을 먼저 처리하는 관문입니다.',
    where: ['overview', 'triage', 'bench', 'architecture', 'problem'] },
  grounding: { term: '라벨 근거 주입', en: 'Label grounding', ko: '라벨 원문을 조회해 판단에 넣는 것', cat: 'ai', aliases: ['라벨 원문 조회', 'grounding'],
    short: '라벨 기재 여부를 모델의 기억에 맡기지 않고, 실제 라벨 원문을 조회해 판단에 넣는 것입니다.',
    where: ['overview', 'triage', 'bench', 'architecture'] },
  critic: { term: '크리틱', en: 'Critic', ko: '근거를 넘는 주장을 반려하는 검사 단계', cat: 'ai', aliases: ['3단 크리틱', 'Critic', 'T1', 'T2', 'T3'],
    short: '에이전트가 쓴 주장을 사람에게 보내기 전에 검사해, 근거를 넘는 주장을 반려하는 단계입니다.',
    long: 'STEP 2에서는 세 단계입니다. T1 근거 ID가 실제로 있는지, T2 문장 속 숫자가 근거 수치와 같은지(숫자 오라클), T3 과잉해석 규칙을 어겼는지 봅니다. 반려되면 사유와 함께 다시 씁니다.',
    where: ['overview', 'problem', 'triage', 'discovery', 'd-critic', 'bench', 'architecture', 'skills', 'cli', 'signals'] },
  oracle: { term: '숫자 오라클', en: 'Numeric oracle', ko: '문장 속 숫자를 원래 수치와 대조하는 검사', cat: 'ai',
    short: '모델이 쓴 문장의 숫자를 SQL로 계산한 원래 수치와 하나하나 대조하는 검사입니다.',
    where: ['triage', 'signals', 'architecture', 'problem', 'skills'] },
  evidenceId: { term: '근거 ID', en: 'Evidence ID', ko: '주장이 기댄 자료의 고유 식별자', cat: 'ai', aliases: ['evidence_ids', 'evidence ID'],
    short: '주장이 기대는 자료(통계 행, 라벨 절, 논문 등)를 가리키는 고유 식별자입니다. 참고문헌 번호처럼 출처를 다시 찾게 해 줍니다.',
    long: 'ID가 있다는 사실만으로 결론이 옳아지지는 않습니다. 그래서 크리틱이 숫자와 해석을 따로 검사합니다.',
    where: ['overview', 'problem', 'triage', 'architecture', 'skills', 'cli', 'agent'] },
  overclaim: { term: '과잉해석', en: 'Overclaim', ko: '근거가 허락하는 범위를 넘는 결론', cat: 'ai', aliases: ['overclaim', '과잉해석 규칙', 'R1'],
    short: '숫자와 출처는 맞는데 결론이 근거가 허락하는 범위를 넘는 주장입니다.',
    long: '예: "PRR이 높으니 이 환자에게 인과가 있다", "다른 단백질보다 도킹 점수가 좋으니 선택적이다". 크리틱은 이런 해석을 막는 13가지 규칙(R1–R13)을 씁니다.',
    where: ['overview', 'problem', 'triage', 'discovery', 'd-critic', 'bench', 'architecture', 'skills', 'signals', 'timemachine'] },
  fallback: { term: '폴백', en: 'Fallback', ko: '주 모델이 응답하지 않을 때의 대체 경로', cat: 'ai', aliases: ['fallback'],
    short: '주 모델이 응답하지 않을 때 순서대로 다른 모델로 넘어가는 대체 경로입니다.',
    where: ['triage', 'architecture'] },
  kbmode: { term: '지식 기반 · 통계 기반 판별', en: 'Knowledge-based vs statistics-based discrimination', ko: '약 이름을 쓰는 판별 · 이름을 가린 판별', cat: 'ai', aliases: ['지식 기반 판별', '통계 기반 판별'],
    short: '지식 기반 판별은 약·반응 이름을 보고 공인된 연관인지 판단하고, 통계 기반 판별은 이름을 가리고 보고 통계만 봅니다.',
    long: '공인된 연관은 지식 기반이 잘 가려내고, 아직 알려지지 않은 새 조합의 순위는 통계가 맡습니다.',
    where: ['overview', 'signals', 'validation', 'architecture', 'triage'] },

  // ─── 에이전트 · 보안 ───
  AgentSkills: { term: 'Agent Skills', en: 'NVIDIA Agent Skills · SKILL.md', ko: '에이전트 능력 패키지 규격', cat: 'agent', aliases: ['SKILL.md', '스킬'],
    short: '에이전트가 쓸 수 있는 능력 하나를 입력·출력 계약, 허용 호스트, 쓰는 모델과 함께 적어 둔 패키지 규격입니다. SKILL.md 파일로 적습니다.',
    where: ['overview', 'mission', 'agent', 'skills', 'architecture', 'bench'] },
  NemoClaw: { term: 'NemoClaw', en: 'NVIDIA NemoClaw', ko: '에이전트를 샌드박스와 함께 배포하는 NVIDIA 구성', cat: 'agent',
    short: 'OpenClaw 에이전트를 OpenShell 샌드박스와 함께 한 벌로 배포·관리하는 NVIDIA 구성(블루프린트)입니다.',
    where: ['overview', 'mission', 'agent', 'cli', 'architecture', 'bench'] },
  OpenShell: { term: 'OpenShell', en: 'NVIDIA OpenShell', ko: '정책으로 통제되는 에이전트 샌드박스', cat: 'agent',
    short: '에이전트를 격리된 샌드박스 안에서 돌리며, 정책이 허용한 네트워크·파일·시스템 호출만 통과시키는 NVIDIA 실행 환경입니다.',
    where: ['overview', 'mission', 'agent', 'cli', 'architecture', 'bench'] },
  OpenClaw: { term: 'OpenClaw', en: 'OpenClaw agent harness', ko: '에이전트 실행 틀(하네스)', cat: 'agent',
    short: '워크스페이스 파일과 스킬을 읽고 도구를 호출하며 일을 하는 에이전트 실행 틀(하네스)입니다.',
    where: ['overview', 'mission', 'agent', 'cli', 'architecture'] },
  sandbox: { term: '샌드박스', en: 'Sandbox', ko: '외부와 격리된 실행 공간', cat: 'agent',
    short: '프로그램을 외부와 격리된 공간에서 돌려, 허락받지 않은 접근을 막는 실행 환경입니다.',
    where: ['overview', 'agent', 'cli'] },
  egress: { term: 'egress 허용 목록', en: 'Egress allowlist · deny-by-default', ko: '밖으로 나가는 연결을 목록에 있는 곳만 여는 방식', cat: 'agent', aliases: ['egress', 'deny-by-default', '허용 호스트'],
    short: '밖으로 나가는 네트워크 연결을 기본으로 모두 막고(deny-by-default), 목록에 적은 호스트만 열어 두는 방식입니다.',
    where: ['overview', 'agent', 'skills', 'architecture'] },
  landlock: { term: 'Landlock · seccomp', en: 'Linux Landlock · seccomp', ko: '리눅스 파일 · 시스템 호출 제한 기능', cat: 'agent', aliases: ['Landlock', 'seccomp'],
    short: '리눅스 보안 기능입니다. Landlock은 읽고 쓸 수 있는 파일 경로를, seccomp는 쓸 수 있는 시스템 호출을 제한합니다.',
    where: ['agent'] },
  heartbeat: { term: '하트비트 · cron', en: 'Heartbeat · cron', ko: '정기 자가 점검 · 예약 실행', cat: 'agent', aliases: ['하트비트', 'cron', 'heartbeat'],
    short: '하트비트는 에이전트가 정해진 간격으로 점검 목록을 스스로 확인하는 작업이고, cron은 정해진 시각에 명령을 자동 실행하는 예약 도구입니다.',
    where: ['agent', 'cli'] },
  trifecta: { term: '치명적 삼박자', en: 'Lethal trifecta', ko: '데이터 유출이 가능해지는 세 조건의 조합', cat: 'agent',
    short: '비공개 데이터 접근, 신뢰할 수 없는 입력, 외부 통신이 한 에이전트에 모이면 데이터가 샐 수 있다는 보안 원칙입니다.',
    where: ['agent'] },
  CLI: { term: 'CLI', en: 'Command-Line Interface', ko: '명령줄 인터페이스', cat: 'agent', aliases: ['flygate CLI'],
    short: '터미널에 글로 명령을 쳐서 프로그램을 쓰는 방식입니다. 글로 누르는 버튼이라고 생각하시면 됩니다.',
    where: ['agent', 'cli'] },

  // ─── 구조생물학 · 신약 탐색 ───
  target: { term: '표적', en: 'Target protein', ko: '약이 붙어 작용하는 단백질', cat: 'bio', aliases: ['target'],
    short: '약이 붙어 작용하는 몸속 단백질입니다.',
    where: ['overview', 'discovery', 'd-msa', 'd-diffdock', 'cli'] },
  PARP1: { term: 'PARP1', en: 'Poly(ADP-ribose) polymerase 1', ko: 'DNA 손상을 고치는 단백질', cat: 'bio',
    short: 'DNA 손상을 고치는 단백질입니다. 니라파립 같은 PARP 억제제가 이 단백질을 막아 암세포를 공격합니다.',
    where: ['overview', 'discovery', 'd-msa', 'd-of3', 'd-diffdock', 'd-boltz', 'cli'] },
  niraparib: { term: '니라파립', en: 'Niraparib', ko: 'PARP1 억제 항암제 · 데모 약물', cat: 'bio', aliases: ['NIRAPARIB'],
    short: 'PARP1을 억제하는 항암제입니다. 이 프로젝트의 데모 약물로, 시판 전 결합 예측과 시판 후 이상사례 보고를 잇습니다.',
    where: ['overview', 'discovery', 'd-of3', 'd-diffdock', 'signals', 'cli'] },
  MSA: { term: 'MSA', en: 'Multiple Sequence Alignment', ko: '상동 서열 정렬', cat: 'bio', aliases: ['MSA-Search', '상동 서열'],
    short: '진화적으로 닮은 단백질 서열(상동 서열)들을 모아 줄 맞춰 늘어놓은 것입니다.',
    long: '어느 부분이 함께 변해 왔는지 보여 주어, 구조 예측 모델이 접힘 모양을 추론하는 재료가 됩니다. MSA-Search는 이 정렬을 만드는 NIM입니다.',
    where: ['overview', 'discovery', 'd-msa', 'd-of3'] },
  OpenFold3: { term: 'OpenFold3', en: 'OpenFold3', ko: '단백질–약물 복합체 구조 예측 모델', cat: 'bio',
    short: '단백질과 약물(리간드)을 함께 넣어 복합체의 3차원 구조를 예측하는 모델입니다.',
    where: ['overview', 'discovery', 'd-msa', 'd-of3'] },
  DiffDock: { term: 'DiffDock', en: 'DiffDock', ko: '약물의 결합 자세를 예측하는 도킹 모델', cat: 'bio',
    short: '약물 분자가 단백질의 어느 자리에 어떤 자세(포즈)로 붙는지 예측하는 도킹 모델입니다.',
    where: ['overview', 'discovery', 'd-diffdock', 'cli'] },
  Boltz2: { term: 'Boltz-2', en: 'Boltz-2', ko: '결합 세기(친화도)를 예측하는 모델', cat: 'bio', aliases: ['Boltz'],
    short: '약물이 단백질에 붙는 세기(친화도)를 구조와 함께 예측하는 모델입니다.',
    where: ['overview', 'discovery', 'd-boltz'] },
  docking: { term: '도킹 · 재도킹', en: 'Docking · Redocking', ko: '결합 자세 계산 · 정답 구조로 되짚는 대조 실험', cat: 'bio', aliases: ['도킹', '재도킹', 'redock'],
    short: '도킹은 약물 분자가 단백질 결합 자리에 어떻게 들어가 붙는지 계산으로 맞춰 보는 일입니다. 재도킹은 결정 구조에서 원래 약물을 빼고 다시 도킹해 제자리를 되찾는지 보는 대조 실험입니다.',
    long: '재도킹에서 1순위 포즈가 원래 자리와 2 Å 이내면 성공으로 봅니다. 재도킹 성공은 도킹 설정이 작동한다는 뜻이지, 새 후보의 결합을 예측했다는 뜻은 아닙니다.',
    where: ['overview', 'problem', 'discovery', 'd-diffdock', 'cli'] },
  pose: { term: '포즈', en: 'Pose', ko: '약물 분자의 위치와 자세 하나', cat: 'bio', aliases: ['pose'],
    short: '도킹이 제안한 약물 분자의 위치와 자세 하나입니다.',
    where: ['discovery', 'd-diffdock', 'cli'] },
  ligand: { term: '리간드', en: 'Ligand', ko: '단백질에 붙는 작은 분자', cat: 'bio',
    short: '단백질에 붙는 작은 분자입니다. 여기서는 약물 분자를 뜻합니다.',
    where: ['discovery', 'd-of3', 'd-diffdock', 'cli'] },
  pLDDT: { term: 'pLDDT', en: 'predicted Local Distance Difference Test', ko: '구조 예측 신뢰도', cat: 'bio',
    short: '구조 예측 모델이 아미노산(잔기)마다 매기는 0~100 신뢰도입니다. 90 이상이면 매우 믿을 만합니다.',
    where: ['overview', 'discovery', 'd-of3'] },
  pTM: { term: 'pTM · ipTM', en: 'predicted (interface) Template Modeling score', ko: '전체 접힘 · 결합면 예측 신뢰도', cat: 'bio', aliases: ['ipTM', 'pTM'],
    short: 'pTM은 전체 접힘 모양에 대한 신뢰도, ipTM은 단백질과 리간드가 맞닿는 면에 대한 신뢰도입니다(0~1).',
    where: ['d-of3'] },
  RMSD: { term: 'RMSD', en: 'Root-Mean-Square Deviation', ko: '결정 구조와의 거리(Å)', cat: 'bio', aliases: ['Cα RMSD', 'CA RMSD'],
    short: '예측한 원자 위치가 실험으로 푼 결정 구조와 평균 몇 Å 떨어졌는지입니다. 작을수록 정확하며, 2 Å 이하면 보통 맞았다고 봅니다.',
    where: ['overview', 'discovery', 'd-of3', 'd-diffdock'] },
  angstrom: { term: 'Å', en: 'Ångström', ko: '옹스트롬 · 0.1 나노미터', cat: 'bio', aliases: ['옹스트롬'],
    short: '0.1 나노미터(100억분의 1 미터)입니다. 원자 사이 거리가 대략 1~2 Å입니다.',
    where: ['overview', 'discovery', 'd-of3', 'd-diffdock'] },
  CA: { term: 'Cα', en: 'Alpha carbon', ko: '아미노산 뼈대의 중심 탄소', cat: 'bio', aliases: ['CA'],
    short: '각 아미노산 뼈대의 중심 탄소 원자입니다. 단백질 전체 모양을 비교할 때 이 원자만 씁니다.',
    where: ['overview', 'discovery', 'd-of3'] },
  Kabsch: { term: 'Kabsch 정렬', en: 'Kabsch alignment', ko: '두 구조를 가장 잘 겹치는 회전·이동 계산', cat: 'bio', aliases: ['Kabsch'],
    short: '두 구조를 회전·이동해 가장 잘 겹치게 맞추는 표준 계산입니다. RMSD를 재기 전에 씁니다.',
    where: ['d-of3'] },
  PDB: { term: 'PDB', en: 'Protein Data Bank (RCSB PDB)', ko: '단백질 3차원 구조 공개 데이터베이스', cat: 'bio', aliases: ['RCSB', '4R6E', 'RCSB PDB'],
    short: '실험으로 푼 단백질 3차원 구조를 모은 공개 데이터베이스입니다. PDB 파일은 그 구조 좌표를 담은 파일입니다.',
    long: '4R6E는 PARP1과 니라파립이 함께 결정화된 구조의 번호로, 예측을 채점하는 정답으로 씁니다.',
    where: ['overview', 'discovery', 'd-of3', 'd-diffdock', 'cli'] },
  cocrystal: { term: '공결정 구조', en: 'Co-crystal structure', ko: '단백질과 약물이 붙은 채로 푼 실험 구조', cat: 'bio', aliases: ['결정 구조'],
    short: '단백질과 약물이 붙은 채로 함께 결정화해 X선으로 푼 실험 구조입니다. 도킹과 구조 예측을 채점하는 정답으로 씁니다.',
    where: ['overview', 'discovery', 'd-of3', 'd-diffdock'] },
  affinity: { term: '친화도', en: 'Binding affinity', ko: '약물이 표적에 붙는 세기', cat: 'bio', aliases: ['affinity'],
    short: '약물이 표적 단백질에 얼마나 세게 붙는지입니다.',
    where: ['overview', 'discovery', 'd-boltz'] },
  pIC50: { term: 'pIC50', en: '−log10(IC50)', ko: '억제 효력', cat: 'bio', aliases: ['pChEMBL', 'IC50'],
    short: '표적의 활성을 절반으로 줄이는 농도(IC50)를 −log로 바꾼 값입니다. 1 커질 때마다 10배 강하게 억제한다는 뜻입니다.',
    long: 'pChEMBL은 ChEMBL이 여러 실험의 효력 값을 같은 −log 척도로 맞춘 값입니다.',
    where: ['d-boltz'] },
  ChEMBL: { term: 'ChEMBL', en: 'ChEMBL (EMBL-EBI)', ko: '화합물 실험 활성값 공개 데이터베이스', cat: 'bio',
    short: '논문과 특허에서 모은 화합물의 실험 활성값을 담은 공개 데이터베이스입니다. 친화도 예측을 채점하는 실측값으로 씁니다.',
    where: ['overview', 'discovery', 'd-boltz'] },
  SMILES: { term: 'SMILES', en: 'Simplified Molecular-Input Line-Entry System', ko: '분자를 한 줄 문자열로 적는 표기법', cat: 'bio',
    short: '분자 구조를 한 줄 문자열로 적는 표기법입니다. 예: 벤젠은 c1ccccc1입니다.',
    where: ['cli'] },
  SDF: { term: 'SDF', en: 'Structure-Data File', ko: '분자 좌표 파일 형식', cat: 'bio',
    short: '분자의 원자 좌표를 담는 파일 형식입니다. 도킹 포즈를 이 형식으로 저장합니다.',
    where: ['cli'] },
  Vina: { term: 'Vina 점수', en: 'AutoDock Vina score (kcal/mol)', ko: '고전 도킹 점수', cat: 'bio', aliases: ['Vina', 'kcal/mol'],
    short: '고전 도킹 프로그램 AutoDock Vina의 점수(kcal/mol)입니다. 더 음수일수록 잘 붙는다고 보지만, 다른 표적끼리는 비교할 수 없습니다.',
    where: ['d-diffdock'] },
  selectivity: { term: '선택성', en: 'Selectivity', ko: '원하는 표적에만 붙는 정도', cat: 'bio',
    short: '약이 원하는 표적에만 붙고 다른 단백질에는 덜 붙는 정도입니다. 서로 다른 단백질의 도킹 점수만으로 말할 수 없습니다.',
    where: ['overview'] },

  // ─── 데이터 · 시스템 ───
  API: { term: 'API', en: 'Application Programming Interface', ko: '프로그램끼리 요청과 응답을 주고받는 창구', cat: 'data',
    short: '프로그램끼리 요청과 응답을 주고받는 창구입니다.',
    where: ['triage', 'cli', 'skills'] },
  JSON: { term: 'JSON', en: 'JavaScript Object Notation', ko: '"항목 이름: 값" 형식의 데이터', cat: 'data',
    short: '"항목 이름: 값"으로 된 텍스트 데이터 형식입니다. 사람과 프로그램이 같은 결과를 읽을 수 있습니다.',
    where: ['bench', 'cli', 'agent', 'architecture'] },
  SQL: { term: 'SQL · DuckDB', en: 'Structured Query Language · DuckDB', ko: '데이터베이스 질의 언어 · 분석용 데이터베이스', cat: 'data', aliases: ['SQL', 'DuckDB'],
    short: 'SQL은 데이터베이스에 묻는 표준 언어이고, DuckDB는 이 프로젝트가 FAERS 웨어하우스로 쓰는 분석용 데이터베이스입니다.',
    long: '불균형 지표는 모두 SQL이 계산하고, 모델은 이 숫자를 만들거나 고치지 않습니다.',
    where: ['overview', 'problem', 'triage', 'signals', 'validation', 'warehouse', 'architecture', 'skills'] },
  warehouse: { term: '웨어하우스', en: 'Data warehouse', ko: '분석용으로 층층이 정리한 데이터베이스', cat: 'data',
    short: '여러 원천 데이터를 정리해 분석하기 좋게 층층이 쌓아 둔 데이터베이스입니다.',
    long: '여기서는 원천(raw) → 정제(core) → 참조(ref) → 불균형 분석(sig) → 운영(ops) 계층으로 나눕니다. 원문은 원천 계층에 그대로 두어 언제든 다시 계산할 수 있습니다.',
    where: ['problem', 'triage', 'signals', 'timemachine', 'warehouse'] },
  caseid: { term: 'caseid · primaryid', en: 'FAERS case ID · report version ID', ko: '사례 번호 · 보고 버전 번호', cat: 'data', aliases: ['caseid', 'primaryid', '중복 제거'],
    short: 'FAERS에서 caseid는 사례 번호, primaryid는 그 사례의 보고 버전 번호입니다. 같은 사례의 최신 버전만 남겨 중복을 없앱니다.',
    where: ['problem', 'triage', 'mission', 'warehouse', 'architecture'] },
  FAERS: { term: 'FAERS', en: 'FDA Adverse Event Reporting System', ko: '미국 FDA 이상사례 보고 시스템', cat: 'pv', aliases: ['AERS'],
    short: '의료인·환자·제약사가 미국 FDA에 낸 이상사례 보고를 모은 공개 데이터베이스입니다. 분기마다 새 파일이 공개됩니다.',
    long: '자발적으로 들어온 보고라 전체 복용자 수(분모)가 없고, 보고가 있다고 약이 원인이라는 뜻은 아닙니다. 구형 AERS는 2012년 3분기까지 쓰던 이전 시스템입니다.',
    where: ['overview', 'problem', 'mission', 'triage', 'signals', 'timemachine', 'validation', 'bench', 'warehouse', 'architecture', 'discovery', 'cli', 'skills'] },

  // ─── 초파리 커넥텀 ───
  connectome: { term: '커넥텀', en: 'Connectome', ko: '뇌 뉴런 연결 배선도', cat: 'brain', aliases: ['connectome'],
    short: '뇌의 뉴런들이 서로 어떻게 연결됐는지 모두 적은 배선도입니다.',
    long: '이 대시보드는 초파리 커넥텀의 층 구조를 에이전트 라우팅의 설계 원리와 시각화로만 씁니다. 임상 판단의 근거는 아닙니다.',
    where: ['problem', 'mission', 'triage', 'korea', 'architecture'] },
  MaleCNS: { term: 'MaleCNS', en: 'Male Central Nervous System connectome v1.0', ko: '수컷 초파리 중추신경계 커넥텀', cat: 'brain',
    short: 'Janelia FlyEM 등이 공개한 수컷 초파리 중추신경계 커넥텀(v1.0)입니다. 뇌 화면은 그중 중앙뇌 49,244개 뉴런을 씁니다.',
    where: ['mission', 'triage', 'architecture'] },
  lateralHorn: { term: 'Lateral horn', en: 'Lateral horn (LH)', ko: '초파리의 선천적 반사 영역', cat: 'brain', aliases: ['측각', 'lateral horn'],
    short: '냄새 같은 감각 신호에 학습 없이 즉시 반응하는 초파리 뇌 영역입니다. FlyVigilance의 반사 판단 층에 대응합니다.',
    where: ['problem', 'architecture'] },
  mushroom: { term: '버섯체', en: 'Mushroom body · Kenyon cell · MBON · DAN · APL', ko: '초파리의 학습 · 기억 영역', cat: 'brain', aliases: ['Kenyon cell', 'MBON', 'DAN', 'APL', 'mushroom body'],
    short: '초파리가 경험을 학습하고 기억하는 뇌 영역입니다. Kenyon cell(KC)이 입력을 희소하게 나눠 담고, 출력 뉴런(MBON)이 읽으며, 도파민 뉴런(DAN)이 가치를 갱신하고, APL 뉴런이 전체 활동을 눌러 희소성을 지킵니다.',
    long: 'FlyVigilance의 신호 기억 층(불균형 통계 · 라벨 · 문헌)과 검토 되먹임에 대응합니다.',
    where: ['problem', 'architecture'] },
  antennal: { term: '안테나엽 · PN', en: 'Antennal lobe · Projection neuron', ko: '감각 입력을 정리하는 영역 · 투사 뉴런', cat: 'brain', aliases: ['PN', 'antennal lobe', 'ORN', 'GRN', 'JO', 'VPN'],
    short: '감각 수용체(ORN 후각, GRN 미각, JO 기계감각, VPN 시각)의 입력을 받아 사구체별로 정리해 위로 넘기는 영역과 그 투사 뉴런(PN)입니다.',
    long: 'FlyVigilance의 데이터 수용과 정규화 · 중복 제거 층에 대응합니다.',
    where: ['problem', 'architecture'] },
  centralComplex: { term: '중심 복합체', en: 'Central complex · EPG · PFL · FB', ko: '방향과 행동을 조율하는 영역', cat: 'brain', aliases: ['EPG', 'PFL', 'FB', 'central complex'],
    short: '방향 감각과 목표 지향 행동을 조율하는 초파리 뇌 영역입니다. FlyVigilance의 Nemotron 숙고(System-2) 층에 대응합니다.',
    where: ['architecture'] },
  GABA: { term: 'GABA성 억제 뉴런', en: 'GABAergic inhibitory neurons', ko: '다른 뉴런의 활동을 누르는 뉴런', cat: 'brain', aliases: ['GABA', 'GABAergic', '억제성'],
    short: '신경전달물질 GABA로 다른 뉴런의 활동을 누르는 뉴런입니다. 근거를 넘는 주장을 막는 크리틱 층에 대응합니다.',
    where: ['problem', 'architecture'] },
  descending: { term: '하행 뉴런', en: 'Descending neurons', ko: '뇌에서 몸으로 명령을 내려보내는 뉴런', cat: 'brain', aliases: ['descending'],
    short: '뇌의 결정을 몸의 운동 회로로 내려보내는 뉴런입니다. 수가 아주 적어 병목이 되며, 사람 검토 큐로 가는 행동 층에 대응합니다.',
    where: ['problem', 'architecture'] },
  FDDD: { term: 'FDDD', en: 'fly-connectome-template', ko: '초파리 커넥텀 시각화 템플릿', cat: 'brain',
    short: '팀원이 만든 초파리 커넥텀 시각화 템플릿입니다. STEP 1 3D 장면의 연출과 색 토큰을 여기서 가져왔습니다.',
    where: ['discovery'] },
}

export const GLOSS_KEYS = Object.keys(GLOSSARY)
export const gloss = (k: string): GlossEntry | undefined => GLOSSARY[k]
