import { useState } from 'react'
import { Card, PageHead } from '../components/ui'
import './CliTutorial.css'
import Term from '../components/Term'
import CliShowcase from '../components/CliShowcase'
import CliExperience from './CliExperience'
import { t } from '../lib/i18n'

const REPO = 'https://github.com/Team-FlyGate/Project-FlyGate'
// 언어에 따라 문구가 바뀌므로 렌더할 때 만듭니다.
const getSteps = () => t(['준비하기', '첫 명령 실행', '결과 읽기', '새 도킹 실행'], ['Get ready', 'First command', 'Read the output', 'Run a new docking'])
const getCommands = () => [
  { name: 'discover', tag: t('저장 결과 + 실시간 도킹', 'Saved results + live docking'), title: t('후보물질 근거 살펴보기', 'Explore candidate evidence'), cmd: 'flygate discover parp1', what: t('저장된 근거를 조회하거나 --live로 단백질과 리간드를 NVIDIA DiffDock에 보내 새 포즈를 계산합니다.', 'Looks up saved evidence, or with --live sends a protein and ligand to NVIDIA DiffDock to compute new poses.'), need: t('저장 결과 조회는 키가 필요 없습니다. --live는 NVIDIA_API_KEY, 네트워크, 단백질 PDB와 리간드 입력이 필요합니다. 위 4단계에 실행 예제가 있습니다.', 'Looking up saved results needs no key. --live needs NVIDIA_API_KEY, network access, a protein PDB file and a ligand input. Step 4 above has a worked example.'), read: t('저장 결과는 candidates, 새 실행은 status와 poses를 봅니다. completed이면 run_dir 안에 포즈 SDF와 response.json이 저장됩니다. evidence_ids로 실행 결과를 식별합니다.', 'For saved results read candidates; for a new run read status and poses. When completed, pose SDF files and response.json are saved in run_dir. evidence_ids identify each run result.') },
  { name: 'signals', tag: t('저장 데이터', 'Stored data'), title: t('이상사례 통계 조회', 'Look up adverse-event statistics'), cmd: 'flygate signals NIRAPARIB --limit 5', what: t('니라파립과 함께 보고된 이상반응의 불균형 지표를 조회합니다.', 'Looks up disproportionality metrics for adverse reactions reported with niraparib (the demo drug).'), need: t('CLI 설치 필요. 저장소의 통계 추출본을 사용하며 API 키는 필요 없습니다.', 'Requires the CLI. Uses the statistics extract bundled in the repository; no API key needed.'), read: t('rows의 prr, ror025, ic025와 sdr을 봅니다. 보고의 연관성이며 인과관계나 발생률을 뜻하지 않습니다.', 'Read prr, ror025, ic025 and sdr in rows. These describe association in reports, not causation or incidence.') },
  { name: 'triage', tag: t('온라인 · Jev', 'Online · Jev'), title: t('보고 한 건의 검토 경로 정하기', 'Route a single report for review'), cmd: 'flygate triage agent/examples/case_niraparib.json --no-outcome', what: t('예제 보고를 읽고 규칙·라벨·7문항 판단을 거쳐 검토 경로를 정합니다.', 'Reads an example report and decides its review route through rules, the drug label and a 7-question judgment.'), need: t('네트워크와 TYPESAFE_API_KEY. 키가 없으면 규칙 기반 결과와 사람 검토 경로로 돌아갈 수 있습니다.', 'Network access and TYPESAFE_API_KEY. Without the key it can fall back to a rule-based result and a human-review route.'), read: t('decision.action과 reasons를 확인하세요. --no-outcome은 평가용 결과 코드를 판단에서 숨깁니다. 보고서를 제출하지 않습니다.', 'Check decision.action and reasons. --no-outcome hides the evaluation outcome code from the judgment. Nothing is submitted.') },
  { name: 'grade', tag: t('온라인 · 근거 조회', 'Online · evidence lookup'), title: t('약물–반응 쌍의 근거 모으기', 'Gather evidence for a drug–reaction pair'), cmd: 'flygate grade NIRAPARIB thrombocytopenia', what: t('혈소판감소증(thrombocytopenia)에 대해 통계, 허가 라벨, 문헌을 모읍니다.', 'Collects statistics, the approved label and literature for thrombocytopenia.'), need: t('외부 자료 조회에 네트워크가 필요합니다. Jev 판단·NVIDIA 재정렬을 사용하려면 해당 키를 설정합니다.', 'External lookups need network access. Set the matching keys to use Jev judgment and NVIDIA reranking.'), read: t('pv_class_name, review_priority, gaps와 evidence_ids를 함께 봅니다. --no-judge로 Jev 문헌 판단을 끌 수 있지만, 전체 오프라인 모드는 아닙니다.', 'Read pv_class_name, review_priority, gaps and evidence_ids together. --no-judge turns off Jev literature judgment, but it is not a full offline mode.') },
  { name: 'critic', tag: t('오프라인 연습 가능', 'Works offline for practice'), title: t('주장이 근거를 넘는지 확인', 'Check whether claims exceed the evidence'), cmd: 'flygate critic agent/examples/claims_niraparib.json --offline', what: t('예제 주장을 근거 ID와 숫자에 대조합니다.', 'Checks example claims against evidence IDs and numbers.'), need: t('--offline은 규칙 검사만 합니다. 전체 모델·가드 검사에는 두 API 키와 네트워크가 필요합니다.', '--offline runs rule checks only. The full model and guard checks need both API keys and network access.'), read: t('verdict와 issues를 확인합니다. human_check는 사람이 확인해야 한다는 뜻이며, 전체 검증 통과를 의미하지 않습니다.', 'Check verdict and issues. human_check means a person must confirm; it does not mean full validation passed.') },
  { name: 'kr-causality', tag: t('온라인 · 두 모델', 'Online · two models'), title: t('국내 보고를 구조화하고 평가', 'Structure and assess a Korean report'), cmd: 'flygate kr-causality agent/examples/kr_report.txt --route', what: t('한국어 예제 보고를 구조화하고 한국형 인과성 평가 항목을 채웁니다.', 'Structures an example Korean-language report and fills in the items of the Korean causality assessment algorithm.'), need: t('NVIDIA_API_KEY, TYPESAFE_API_KEY와 네트워크. --route는 한국 규정 모드의 검토 경로도 계산합니다.', 'NVIDIA_API_KEY, TYPESAFE_API_KEY and network access. --route also computes the review route under Korean regulatory rules.'), read: t('items, missing, needs_review와 평가 결과를 함께 확인하세요. 최종 인과성 판정과 보고 제출은 사람이 합니다.', 'Check items, missing, needs_review and the assessment result together. The final causality decision and any submission are made by a person.') },
  { name: 'watch', tag: t('로컬 파일 저장', 'Writes local files'), title: t('감시 목록을 정기 점검', 'Routinely re-check the watchlist'), cmd: 'flygate watch --memory-dir ./tutorial-memory', what: t('감시 목록을 다시 계산하고 날짜별 메모와 사람 검토 대기열을 만듭니다.', 'Recomputes the watchlist and writes a dated note plus a human-review queue.'), need: t('지정한 폴더에 메모·상태 파일을 씁니다. 기본은 오프라인이며 --online은 외부 조회를 켭니다.', 'Writes note and state files to the given folder. Offline by default; --online enables external lookups.'), read: t('review_queue와 memory_note를 확인합니다. 한 번 실행하는 명령입니다. 반복 실행은 별도의 cron 설정이 필요합니다.', 'Check review_queue and memory_note. The command runs once; repeated runs need a separate cron setup.') },
]

function Code({ text, label = t('터미널에 붙여넣기', 'Paste into your terminal') }: { text: string; label?: string }) {
  const [status, setStatus] = useState('')
  async function copy() {
    try { await navigator.clipboard.writeText(text); setStatus(t('복사했습니다', 'Copied')) }
    catch {
      const input = document.createElement('textarea'); input.value = text
      input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input)
      const previous = document.activeElement as HTMLElement | null
      input.select()
      let copied = false
      try { copied = document.execCommand('copy') } catch { /* Manual selection remains available. */ }
      input.remove(); previous?.focus()
      setStatus(copied ? t('복사했습니다', 'Copied') : t('복사할 수 없습니다. 아래 명령을 직접 선택해 주세요.', 'Could not copy. Please select the command below manually.'))
    }
  }
  return <div className="cli-code"><div className="cli-code-head"><span>{label}</span><button className="btn ghost" onClick={copy} aria-label={t(`${label} 복사`, `Copy: ${label}`)}>{t('복사', 'Copy')}</button></div><pre tabIndex={0}><code>{text}</code></pre><span className="cli-copy-status" role="status">{status}</span></div>
}

export default function CliTutorial() {
  const [step, setStep] = useState(0)
  const [selected, setSelected] = useState('discover')
  const [target, setTarget] = useState('parp1')
  const [filter, setFilter] = useState('')
  const [mode, setMode] = useState<'chat' | 'shell'>('chat')
  const steps = getSteps()
  const commands = getCommands()
  const command = commands.find(c => c.name === selected)!
  const visible = commands.filter(c => `${c.name} ${c.title} ${c.what}`.toLowerCase().includes(filter.toLowerCase()))
  return <div className="page cli-tutorial">
    <PageHead eyebrow="AGENT TOOLKIT / FLYGATE CLI / GUIDE v2.0.0" title={t(<>연구의 다음 단계, <span className="cli-accent">FlyGate CLI</span></>, <>The next step in research: <span className="cli-accent">FlyGate CLI</span></>)} lede={t('실제 터미널 화면과 동작 데모로 먼저 만나고, 설치부터 첫 분석까지 차례로 시작하세요.', 'See real terminal screens and a working demo first, then go step by step from installation to your first analysis.')} right={<a className="btn ghost" href="#/agent">{t('에이전트 구성 보기 ↗', 'View agent setup ↗')}</a>} />
    <CliExperience />
    <CliShowcase />
    <div id="cli-install" />
    <Card title={t('설치했다면, flygate로 시작하세요', 'Installed? Start with flygate')} sub={t('한 줄 입력창 · 슬래시 명령 · 확인 후 실행', 'Single-line prompt · slash commands · run after confirmation')} className="cli-guide">
      <Code text="flygate" label={t('일반 터미널에서 대화형 FlyGate 시작', 'Start interactive FlyGate from a regular terminal')} />
      <p>{t('첫 실행에 NVIDIA 키가 없으면 공식 발급 페이지를 열고 숨김 입력으로 설정합니다. Jev 키는 선택 사항이며 Enter로 건너뛸 수 있습니다. OS 보안 저장소에 저장하도록 선택하면 다음 실행부터 불러옵니다. 자동 로그인으로 키를 발급하는 방식은 아닙니다.', 'If no NVIDIA key is set on first run, FlyGate opens the official key page and lets you enter the key through hidden input. The Jev key is optional; press Enter to skip it. If you choose to store keys in the OS secure keychain, they load automatically next time. Keys are not issued through automatic sign-in.')}</p>
      {t(<p>채팅창에서는 <code>/discover parp1</code>을 입력하거나 “PARP1 후보 근거를 보여줘”라고 요청하세요. 실행 명령을 확인한 뒤 <code>y</code>로 승인합니다. Enter는 전송, Alt+Enter 또는 Ctrl+J는 줄바꿈입니다. 마우스·트랙패드로 이전 출력을 스크롤할 수 있습니다.</p>, <p>In the chat, type <code>/discover parp1</code> or ask “Show me the evidence for PARP1 candidates.” Review the command to be run, then approve it with <code>y</code>. Enter sends; Alt+Enter or Ctrl+J inserts a line break. Scroll back through earlier output with a mouse or trackpad.</p>)}
    </Card>
    <div className="cli-concepts"><div><b>NVIDIA <Term k="NemoClaw" /></b><span>{t('배포·관리 기반', 'Deployment and management layer')}</span></div><span>→</span><div><b><Term k="OpenClaw" /> + <Term k="OpenShell" /></b><span>{t('에이전트 실행 + 격리·정책', 'Agent runtime + isolation and policy')}</span></div><span>→</span><div><b>FlyGate CLI</b><span>{t('팀이 개발한 분석 도구', 'Analysis tools built by our team')}</span></div></div>
    <Card title={t('처음부터 따라 하기', 'Follow along from scratch')} sub={t('Mac·Linux 터미널 또는 Windows WSL의 bash/zsh 기준입니다. 명령은 한 블록씩 실행하세요.', 'Written for bash/zsh in a Mac or Linux terminal, or Windows WSL. Run the commands one block at a time.')} className="cli-guide">
      <div className="cli-steps" role="tablist" aria-label={t('튜토리얼 단계', 'Tutorial steps')}>{steps.map((s, i) => <button key={s} role="tab" id={`cli-tab-${i}`} aria-selected={step === i} aria-controls="cli-step-panel" tabIndex={step === i ? 0 : -1} onKeyDown={e => {
        const next = e.key === 'ArrowRight' ? (i + 1) % 4 : e.key === 'ArrowLeft' ? (i + 3) % 4 : e.key === 'Home' ? 0 : e.key === 'End' ? 3 : null
        if (next !== null) { e.preventDefault(); setStep(next); document.getElementById(`cli-tab-${next}`)?.focus() }
      }} className={step === i ? 'active' : ''} onClick={() => setStep(i)}><span>0{i + 1}</span>{s}</button>)}</div>
      <div id="cli-step-panel" role="tabpanel" aria-labelledby={`cli-tab-${step}`} className="cli-step-body">
        {step === 0 && t(<><h3>01 / 내 컴퓨터에 준비하기</h3><p>Mac은 ‘터미널’, Windows는 WSL의 Ubuntu 터미널을 여세요. Python 3.10 이상과 Git이 필요합니다. 아래 명령은 설치 여부와 버전을 보여 줍니다.</p><Code text={'python3 --version\ngit --version'} label="준비 상태 확인" /><p>코드 저장소를 내 컴퓨터로 내려받고 그 폴더로 이동합니다. 이미 받은 저장소가 있다면 해당 폴더를 열면 됩니다.</p><Code text={'git clone https://github.com/Team-FlyGate/Project-FlyGate.git\ncd Project-FlyGate'} label="저장소 받기" /><p>설치 스크립트는 프로젝트 전용 Python 환경(.venv)과 필요한 패키지를 만들고, 사용자 폴더에 flygate 명령을 연결합니다.</p><Code text={'./scripts/install_flygate.sh\nexport PATH="$HOME/.local/bin:$PATH"\nflygate --help'} label="CLI 설치 및 도움말 확인" /><div className="cli-tip">성공하면 triage, grade, signals 등 7개 명령 목록이 나옵니다. export 줄은 현재 터미널에 명령의 위치를 알려 줍니다. 첫 실습에는 API 키나 전체 FAERS 데이터 다운로드가 필요 없습니다.</div></>, <><h3>01 / Get your computer ready</h3><p>Open Terminal on a Mac, or the Ubuntu terminal in WSL on Windows. You need Python 3.10 or later and Git. The commands below show whether they are installed and which versions you have.</p><Code text={'python3 --version\ngit --version'} label="Check prerequisites" /><p>Download the code repository to your computer and move into that folder. If you already have the repository, just open that folder.</p><Code text={'git clone https://github.com/Team-FlyGate/Project-FlyGate.git\ncd Project-FlyGate'} label="Get the repository" /><p>The install script creates a project-specific Python environment (.venv) with the required packages and links the flygate command into your user folder.</p><Code text={'./scripts/install_flygate.sh\nexport PATH="$HOME/.local/bin:$PATH"\nflygate --help'} label="Install the CLI and show help" /><div className="cli-tip">On success you will see a list of 7 commands such as triage, grade and signals. The export line tells the current terminal where the command lives. The first exercise needs no API key and no full FAERS (FDA Adverse Event Reporting System) download.</div></>)}
        {step === 1 && t(<><h3>02 / 저장된 후보 탐색 결과 읽기</h3><p>설치를 마쳤다면 표적을 고르고 명령을 복사하세요. 모든 예제는 저장소의 최상위 폴더에서 실행합니다.</p><label className="cli-select">살펴볼 표적<select value={target} onChange={e => setTarget(e.target.value)}><option value="parp1">PARP1 · 니라파립 예제</option><option value="xa">Factor Xa</option><option value="cox2">COX-2</option></select></label><Code text={`flygate discover ${target}`} /><p>여러 줄의 JSON이 나오면 정상입니다. JSON은 ‘항목 이름: 값’으로 구성된 결과표이며, 사람과 프로그램이 같은 결과를 읽을 수 있게 합니다.</p><div className="cli-tip"><strong>이 실습이 하는 일</strong><br />이미 계산해 둔 실측과 검증 결과를 불러옵니다. 새로운 구조 예측·도킹·모델 호출은 실행하지 않습니다.</div><h4>결과를 파일로 보관하려면</h4><Code text={`flygate discover ${target} > discovery-result.json`} label="JSON 파일 저장" /><p className="note">현재 폴더에 파일을 만듭니다. 같은 이름의 파일이 있으면 덮어쓰므로 다른 이름을 사용하세요.</p></>, <><h3>02 / Read saved candidate-discovery results</h3><p>Once installed, pick a target and copy the command. Run every example from the top-level folder of the repository.</p><label className="cli-select">Target to explore<select value={target} onChange={e => setTarget(e.target.value)}><option value="parp1">PARP1 · niraparib example</option><option value="xa">Factor Xa</option><option value="cox2">COX-2</option></select></label><Code text={`flygate discover ${target}`} /><p>Several lines of JSON output means it worked. JSON is a results table made of “field name: value” pairs, so people and programs can read the same result.</p><div className="cli-tip"><strong>What this exercise does</strong><br />It loads measurements and validation results computed in advance. It does not run any new structure prediction, docking or model call.</div><h4>To keep the result as a file</h4><Code text={`flygate discover ${target} > discovery-result.json`} label="Save as a JSON file" /><p className="note">This creates a file in the current folder. A file with the same name will be overwritten, so pick a different name if needed.</p></>)}
        {step === 2 && t(<><h3>03 / 숫자보다 먼저, 출처를 읽기</h3><p>긴 출력 전체를 한 번에 이해할 필요는 없습니다. 아래는 구조를 설명하기 위해 줄인 예시입니다.</p><Code label="출력 구조 예시 · 실행 명령이 아닙니다" text={'{\n  "cmd": "discover",\n  "candidates": [\n    { "ligand": "Niraparib",\n      "evidence_ids": ["vina:parp1/Niraparib"] }\n  ]\n}'} /><dl className="cli-fields"><div><dt>cmd</dt><dd>어떤 명령의 결과인지 확인합니다. 영수증의 거래 종류와 같습니다.</dd></div><div><dt>candidates</dt><dd>비교할 후보 목록입니다. 후보별 예측값과 실험 참조값을 구분해 읽습니다.</dd></div><div><dt>evidence_ids</dt><dd>근거를 다시 찾기 위한 식별자입니다. 참고문헌 번호처럼 출처를 가리키지만, ID가 있다는 사실만으로 결론이 옳아지는 것은 아닙니다.</dd></div><div><dt>decision / verdict</dt><dd>다른 명령에서 나오는 경로·검증 결과입니다. human_check와 human_review는 사람이 확인해야 한다는 뜻입니다.</dd></div></dl><div className="cli-tip">도킹 점수는 약효 입증이 아니고, 이상사례 통계는 인과관계 확정이 아닙니다. 숫자와 함께 원자료·비교 조건·검토 사유를 읽어 주세요.</div></>, <><h3>03 / Read the source before the numbers</h3><p>You don't need to understand the whole long output at once. Below is a shortened example that shows the structure.</p><Code label="Example output structure · not a command to run" text={'{\n  "cmd": "discover",\n  "candidates": [\n    { "ligand": "Niraparib",\n      "evidence_ids": ["vina:parp1/Niraparib"] }\n  ]\n}'} /><dl className="cli-fields"><div><dt>cmd</dt><dd>Which command produced the result, like the transaction type on a receipt.</dd></div><div><dt>candidates</dt><dd>The list of candidates to compare. Read each candidate's predicted values separately from experimental reference values.</dd></div><div><dt>evidence_ids</dt><dd>Identifiers for finding the evidence again. Like reference numbers, they point to a source, but having an ID does not by itself make a conclusion correct.</dd></div><div><dt>decision / verdict</dt><dd>Routing and validation results from other commands. human_check and human_review mean a person must confirm.</dd></div></dl><div className="cli-tip">A docking score does not prove efficacy, and adverse-event statistics do not establish causation. Read the numbers together with the raw data, the comparison conditions and the reasons for review.</div></>)}
        {step === 3 && t(<><h3>04 / NVIDIA DiffDock으로 새 도킹 실행하기</h3><p>단백질 구조와 <Term k="ligand">리간드</Term>(단백질에 붙는 약물 분자)를 NVIDIA <Term k="DiffDock" /> <Term k="NIM" ko />에 보내 새로운 결합 <Term k="pose">포즈</Term>(붙는 위치와 자세)를 계산합니다. API 키는 서비스 이용 자격 증명이며, 연결된 계정의 사용량·비용이 발생할 수 있습니다.</p><p>대화형 CLI에서 <code>/login</code>을 입력해 NVIDIA API 키를 숨김 입력으로 설정하세요. Jev 키는 선택 사항이며 도킹에는 필요 없습니다. 키는 이 웹사이트나 채팅 메시지에 붙여넣지 않습니다.</p><Code label="FlyGate 채팅창에서 API 키 설정" text="/login" /><p>아래 명령은 일반 터미널용입니다. FlyGate 채팅창에서는 앞의 <code>flygate discover</code>를 <code>/discover</code>로 바꾸어 실행할 수 있습니다.</p><p>저장소에 포함된 <Term k="PARP1" /> 예측 구조와 니라파립 <Term k="SMILES" />(분자를 한 줄로 표현한 문자열)로 첫 도킹을 실행해 보세요. 이 명령은 실제 API 요청을 보냅니다.</p><Code text="flygate discover --live --protein fly_discovery/measurements/nim/of3_parp1_niraparib.pdb --ligand-file agent/examples/niraparib.smi --num-poses 5 --timeout 300" label="새 도킹 실행 · NVIDIA API 사용" />
          <dl className="cli-fields"><div><dt>--protein</dt><dd>단백질 <Term k="PDB">PDB</Term>(단백질 3차원 구조) 파일 경로입니다. 자신의 구조 파일로 바꿀 수 있습니다.</dd></div><div><dt>--ligand-file</dt><dd>한 분자의 <Term k="SDF" /> 또는 <Term k="SMILES" /> 파일입니다. --smiles 옵션으로 문자열을 직접 지정할 수도 있습니다.</dd></div><div><dt>--num-poses</dt><dd>계산할 결합 포즈 수입니다. 1~20개 중 선택합니다.</dd></div><div><dt>status / run_dir</dt><dd>completed이면 완료입니다. 출력된 폴더에서 pose_01.sdf, response.json, manifest.json을 확인합니다. pending이면 같은 작업을 이어서 조회합니다.</dd></div></dl>
          <Code text={'flygate discover --resume data/discovery-runs/<출력된_run_id>'} label="대기 중인 요청 이어서 조회 · 경로를 바꿔 주세요" />
          <p>실행마다 새 폴더를 만들어 입력·출력·근거 ID를 보존합니다. 통신 중단 시 새 작업을 자동 제출하지 않습니다. 신뢰도는 포즈에 대한 모델 점수이며 친화도 측정값과는 다릅니다.</p>
          <h4>다음 실습: 약물감시</h4><Code text={'flygate triage agent/examples/case_niraparib.json --no-outcome'} label="예제 보고 분류" /><p><code>decision.action</code>은 다음 처리 경로, <code>decision.reasons</code>는 그 이유입니다. 예제 파일은 저장소에 포함되어 있습니다.</p><div className="cli-tip">키가 없거나 모델을 사용할 수 없으면 명령에 따라 오류·제한 모드·사람 확인 결과가 나올 수 있습니다. ‘모델 미실행’을 ‘검증 통과’로 해석하지 마세요.</div><p><a href="https://build.nvidia.com" target="_blank" rel="noreferrer">NVIDIA API 서비스 ↗</a> · <a href="https://www.typesafe.ai" target="_blank" rel="noreferrer">TypeSafe AI ↗</a></p></>, <><h3>04 / Run a new docking with NVIDIA DiffDock</h3><p>Send a protein structure and a <Term k="ligand">ligand</Term> (the drug molecule that binds to the protein) to the NVIDIA <Term k="DiffDock" /> <Term k="NIM" ko /> (NVIDIA Inference Microservice) to compute new binding <Term k="pose">poses</Term> (where and how the molecule sits). The API key is your credential for the service; usage and charges may apply to the linked account.</p><p>In the interactive CLI, type <code>/login</code> to set the NVIDIA API key through hidden input. The Jev key is optional and not needed for docking. Never paste keys into this website or into chat messages.</p><Code label="Set API keys in the FlyGate chat" text="/login" /><p>The command below is for a regular terminal. In the FlyGate chat, replace the leading <code>flygate discover</code> with <code>/discover</code>.</p><p>Try your first docking with the predicted <Term k="PARP1" /> structure bundled in the repository and the niraparib <Term k="SMILES" /> (a one-line text representation of a molecule). This command sends a real API request.</p><Code text="flygate discover --live --protein fly_discovery/measurements/nim/of3_parp1_niraparib.pdb --ligand-file agent/examples/niraparib.smi --num-poses 5 --timeout 300" label="Run a new docking · uses the NVIDIA API" />
          <dl className="cli-fields"><div><dt>--protein</dt><dd>Path to the protein <Term k="PDB">PDB</Term> (3D protein structure) file. You can substitute your own structure file.</dd></div><div><dt>--ligand-file</dt><dd>An <Term k="SDF" /> or <Term k="SMILES" /> file with one molecule. You can also pass the string directly with --smiles.</dd></div><div><dt>--num-poses</dt><dd>Number of binding poses to compute, from 1 to 20.</dd></div><div><dt>status / run_dir</dt><dd>completed means done. Check pose_01.sdf, response.json and manifest.json in the printed folder. If pending, query the same job again.</dd></div></dl>
          <Code text={'flygate discover --resume data/discovery-runs/<printed_run_id>'} label="Resume a pending request · replace the path" />
          <p>Each run creates a new folder that keeps its inputs, outputs and evidence IDs. If the connection drops, no new job is submitted automatically. Confidence is the model's score for a pose, not a measured binding affinity.</p>
          <h4>Next exercise: pharmacovigilance</h4><Code text={'flygate triage agent/examples/case_niraparib.json --no-outcome'} label="Triage an example report" /><p><code>decision.action</code> is the next handling route and <code>decision.reasons</code> explains why. The example file is included in the repository.</p><div className="cli-tip">Without keys, or when a model is unavailable, a command may return an error, a limited mode or a human-check result. Never read “model not run” as “validation passed”.</div><p><a href="https://build.nvidia.com" target="_blank" rel="noreferrer">NVIDIA API service ↗</a> · <a href="https://www.typesafe.ai" target="_blank" rel="noreferrer">TypeSafe AI ↗</a></p></>)}
      </div>
      <div className="cli-step-footer"><button className="btn ghost" disabled={step === 0} onClick={() => setStep(step - 1)}>{t('← 이전', '← Back')}</button><span aria-live="polite">{step + 1} / {steps.length}</span><button className="btn" disabled={step === 3} onClick={() => setStep(step + 1)}>{t('다음 단계 →', 'Next step →')}</button></div>
    </Card>
    <Card title={t('내가 하려는 일로 명령 찾기', 'Find a command by what you want to do')} sub={t('각 명령의 준비물과 결과 읽는 방법을 함께 확인하세요.', 'See what each command needs and how to read its output.')} className="cli-catalog"><label className="cli-search">{t('명령 검색', 'Search commands')}<input value={filter} onChange={e => setFilter(e.target.value)} placeholder={t('예: 문헌, 보고, discover', 'e.g. literature, report, discover')} /></label><div className="cli-catalog-grid"><div className="cli-command-list">{visible.map(c => <button key={c.name} aria-pressed={selected === c.name} className={selected === c.name ? 'active' : ''} onClick={() => setSelected(c.name)}><code>/{c.name}</code><span>{c.title}</span></button>)}{!visible.length && <p role="status">{t('일치하는 명령이 없습니다. 다른 단어로 검색해 주세요.', 'No matching command. Try a different word.')}</p>}</div><div className="cli-command-detail"><span className="chip">{command.tag}</span><h3>{command.title}</h3><p>{command.what}</p><div className="cli-mode-switch" aria-label={t('명령 입력 위치', 'Where to type the command')}><button className={mode === 'chat' ? 'active' : ''} aria-pressed={mode === 'chat'} onClick={() => setMode('chat')}>{t('FlyGate 채팅창', 'FlyGate chat')}</button><button className={mode === 'shell' ? 'active' : ''} aria-pressed={mode === 'shell'} onClick={() => setMode('shell')}>{t('일반 터미널', 'Regular terminal')}</button></div><Code text={mode === 'chat' ? command.cmd.replace(/^flygate /, '/') : command.cmd} label={mode === 'chat' ? t('채팅창에 입력 · 승인 후 실행', 'Type in the chat · runs after approval') : t('터미널에 입력 · 바로 실행', 'Type in the terminal · runs immediately')} /><h4>{t('실행 전에', 'Before you run it')}</h4><p>{command.need}</p><h4>{t('결과에서 볼 것', 'What to look for in the output')}</h4><p>{command.read}</p><Code text={mode === 'chat' ? `/${command.name} --help` : `flygate ${command.name} --help`} label={t('이 명령의 전체 옵션 확인', 'Show all options for this command')} /></div></div></Card>
    <Card title={t('막혔을 때 확인할 것', 'If you get stuck')} className="cli-faq">{t([
      ['command not found: flygate', '명령 위치를 못 찾은 상태입니다. 위 설치 단계의 export PATH 줄을 다시 실행하세요. 저장소 폴더에서는 ./agent/bin/flygate --help로도 확인할 수 있습니다.'],
      ['python3 또는 git을 찾을 수 없어요', '첫 단계의 준비 도구가 없습니다. python.org와 git-scm.com의 운영체제별 설치 안내를 따라 설치한 뒤 터미널을 새로 여세요. Windows PowerShell 대신 WSL 터미널을 사용합니다.'],
      ['No such file / 파일을 찾을 수 없어요', '현재 위치가 Project-FlyGate 최상위 폴더인지 확인하세요. 그 안에 agent와 scripts 폴더가 보여야 합니다. 예제 경로는 이 위치를 기준으로 합니다.'],
      ['ModuleNotFoundError', '필요한 Python 패키지가 없거나 다른 Python 환경으로 실행했을 수 있습니다. ./scripts/install_flygate.sh를 실행한 뒤 flygate 명령으로 다시 시도하세요.'],
      ['401·403, not configured, human_check', '키 누락·권한 문제·검사 미실행을 구분해야 합니다. 오류 메시지를 확인하고 /login에서 키를 설정한 뒤 서비스 이용 가능 상태를 확인하세요. 사람 확인 표시는 검증 통과가 아닙니다.'],
      ['실행이 오래 걸리거나 429가 나와요', '라벨·문헌 조회와 모델 응답에는 시간이 걸립니다. 429는 요청량 제한일 수 있습니다. 연속 재시도 대신 서비스 상태와 할당량을 확인하세요.'],
      ['전체 데이터나 NemoClaw 설치도 필요한가요?', '첫 discover 실습에는 필요 없습니다. 전체 FAERS 재현은 별도 데이터 다운로드가 필요합니다. NemoClaw 배포는 CLI를 에이전트의 도구로 쓰는 다음 단계이며, 에이전트 문서에서 안내합니다.'],
    ], [
      ['command not found: flygate', 'Your shell cannot find the command. Re-run the export PATH line from the install step above. From the repository folder you can also check with ./agent/bin/flygate --help.'],
      ['python3 or git not found', 'The prerequisites from step one are missing. Install them following the OS-specific instructions at python.org and git-scm.com, then open a new terminal. On Windows, use a WSL terminal rather than PowerShell.'],
      ['No such file / file not found', 'Make sure you are in the top-level Project-FlyGate folder; you should see the agent and scripts folders there. Example paths are relative to this location.'],
      ['ModuleNotFoundError', 'A required Python package is missing, or a different Python environment was used. Run ./scripts/install_flygate.sh and try again with the flygate command.'],
      ['401·403, not configured, human_check', 'Distinguish a missing key, a permission problem and a check that did not run. Read the error message, set keys with /login, and confirm the service is available. A human-check flag does not mean validation passed.'],
      ['It runs slowly, or returns 429', 'Label and literature lookups and model responses take time. 429 may mean a rate limit. Check the service status and your quota instead of retrying repeatedly.'],
      ['Do I also need the full dataset or NemoClaw?', 'Not for the first discover exercise. Reproducing the full FAERS (FDA Adverse Event Reporting System) analysis requires a separate data download. Deploying NemoClaw is the next step, where the CLI becomes a tool for the agent; the agent documentation covers it.'],
    ]).map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</Card>
    <footer className="cli-source"><span>{t('이제 근거를 직접 살펴볼 준비가 됐습니다.', 'You are ready to examine the evidence yourself.')}</span><div><a href={`${REPO}/blob/main/agent/flygate.py`} target="_blank" rel="noreferrer">{t('CLI 구현 ↗', 'CLI source ↗')}</a><a href={`${REPO}/blob/main/docs/AGENT.md`} target="_blank" rel="noreferrer">{t('에이전트 배포 안내 ↗', 'Agent deployment guide ↗')}</a><a href="#/discovery">{t('FlyDiscovery 화면 →', 'FlyDiscovery view →')}</a></div></footer>
  </div>
}
